In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/sample_submission.csv
/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/store.csv
/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/train.csv
/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/test.csv

In [2]:
import pandas as pd
import numpy as np 

df=pd.read_csv("/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/train.csv")

/tmp/ipykernel_58/2966784180.py:4: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/train.csv")

In [3]:
df

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1,2,5,2015-07-31,6064,625,1,1,0,1
2,3,5,2015-07-31,8314,821,1,1,0,1
3,4,5,2015-07-31,13995,1498,1,1,0,1
4,5,5,2015-07-31,4822,559,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1
1017205,1112,2,2013-01-01,0,0,0,0,a,1
1017206,1113,2,2013-01-01,0,0,0,0,a,1
1017207,1114,2,2013-01-01,0,0,0,0,a,1
1017208,1115,2,2013-01-01,0,0,0,0,a,1

In [4]:
df_store=pd.read_csv("/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/store.csv")

In [5]:
df_store

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [6]:
df.isnull().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isna().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [9]:
df.dtypes

Store             int64
DayOfWeek         int64
Date             object
Sales             int64
Customers         int64
Open              int64
Promo             int64
StateHoliday     object
SchoolHoliday     int64
dtype: object

In [10]:
df[df["Store"]==1]

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
0,1,5,2015-07-31,5263,555,1,1,0,1
1115,1,4,2015-07-30,5020,546,1,1,0,1
2230,1,3,2015-07-29,4782,523,1,1,0,1
3345,1,2,2015-07-28,5011,560,1,1,0,1
4460,1,1,2015-07-27,6102,612,1,1,0,1
...,...,...,...,...,...,...,...,...,...
1011635,1,6,2013-01-05,4997,635,1,0,0,1
1012750,1,5,2013-01-04,4486,619,1,0,0,1
1013865,1,4,2013-01-03,4327,578,1,0,0,1
1014980,1,3,2013-01-02,5530,668,1,0,0,1
1016095,1,2,2013-01-01,0,0,0,0,a,1

In [11]:
df_sample=pd.read_csv("/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/sample_submission.csv")
df_sample

          Id  Sales
0          1      0
1          2      0
2          3      0
3          4      0
4          5      0
...      ...    ...
41083  41084      0
41084  41085      0
41085  41086      0
41086  41087      0
41087  41088      0

[41088 rows x 2 columns]

In [12]:
(df["Sales"]==0).sum()

np.int64(172871)

In [13]:
df_test=pd.read_csv("/kaggle/input/datasets/nonameexi/sales-and-demand-forecasting/test.csv")
df_test

,Id,Store,DayOfWeek,Date,Open,Promo,StateHoliday,SchoolHoliday
0,1,1,4,2015-09-17,1.0,1,0,0
1,2,3,4,2015-09-17,1.0,1,0,0
2,3,7,4,2015-09-17,1.0,1,0,0
3,4,8,4,2015-09-17,1.0,1,0,0
4,5,9,4,2015-09-17,1.0,1,0,0
...,...,...,...,...,...,...,...,...
41083,41084,1111,6,2015-08-01,1.0,0,0,0
41084,41085,1112,6,2015-08-01,1.0,0,0,0
41085,41086,1113,6,2015-08-01,1.0,0,0,0
41086,41087,1114,6,2015-08-01,1.0,0,0,0
41087,41088,1115,6,2015-08-01,1.0,0,0,1

In [14]:
import pandas as pd
train = df.copy()
train["Date"]= pd.to_datetime(df["Date"])
print("Minimum Date ",train["Date"].min())
print("Maximum Date",train["Date"].max())
print("Number of Unique dates ", train["Date"].nunique())

Minimum Date  2013-01-01 00:00:00
Maximum Date 2015-07-31 00:00:00
Number of Unique dates  942

In [15]:
train["Date"].sort_values().head().tolist()

[Timestamp('2013-01-01 00:00:00'),
 Timestamp('2013-01-01 00:00:00'),
 Timestamp('2013-01-01 00:00:00'),
 Timestamp('2013-01-01 00:00:00'),
 Timestamp('2013-01-01 00:00:00')]

In [16]:
train["Date"].sort_values().tail().tolist()

[Timestamp('2015-07-31 00:00:00'),
 Timestamp('2015-07-31 00:00:00'),
 Timestamp('2015-07-31 00:00:00'),
 Timestamp('2015-07-31 00:00:00'),
 Timestamp('2015-07-31 00:00:00')]

In [17]:
daily_counts = train.groupby("Date")["Store"].count()
print(daily_counts.describe())
print("Smallest No of Counts", daily_counts.nsmallest(10))
print("Largest No of Counts", daily_counts.nlargest(10))

count     942.000000
mean     1079.839703
std        71.399080
min       935.000000
25%      1115.000000
50%      1115.000000
75%      1115.000000
max      1115.000000
Name: Store, dtype: float64
Smallest No of Counts Date
2014-07-01    935
2014-07-02    935
2014-07-03    935
2014-07-04    935
2014-07-05    935
2014-07-06    935
2014-07-07    935
2014-07-08    935
2014-07-09    935
2014-07-10    935
Name: Store, dtype: int64
Largest No of Counts Date
2013-01-02    1115
2013-01-03    1115
2013-01-04    1115
2013-01-05    1115
2013-01-06    1115
2013-01-07    1115
2013-01-08    1115
2013-01-09    1115
2013-01-10    1115
2013-01-11    1115
Name: Store, dtype: int64

In [18]:
print("Open distribution:")
print(train["Open"].value_counts())

print("\nSales = 0:")
print((train["Sales"] == 0).sum())

print("\nSales > 0:")
print((train["Sales"] > 0).sum())

print("\nSales = 0 while Open = 1:")
print(((train["Sales"] == 0) & (train["Open"] == 1)).sum())

Open distribution:
Open
1    844392
0    172817
Name: count, dtype: int64

Sales = 0:
172871

Sales > 0:
844338

Sales = 0 while Open = 1:
54

In [19]:
train.groupby("Open")["Sales"].apply(lambda x: (x == 0).sum())

Open
0    172817
1        54
Name: Sales, dtype: int64

In [20]:
zero_open_sales = train[
    (train["Open"] == 1) &
    (train["Sales"] == 0)
]

zero_open_sales.head(20)

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday
86825,971,5,2015-05-15,0,0,1,0,0,1
142278,674,4,2015-03-26,0,0,1,0,0,0
196938,699,4,2015-02-05,0,0,1,1,0,0
322053,708,3,2014-10-01,0,0,1,1,0,0
330176,357,1,2014-09-22,0,0,1,0,0,0
340348,227,4,2014-09-11,0,0,1,0,0,0
340860,835,4,2014-09-11,0,0,1,0,0,0
341795,835,3,2014-09-10,0,0,1,0,0,0
346232,548,5,2014-09-05,0,0,1,1,0,1
346734,28,4,2014-09-04,0,0,1,1,0,0
347669,28,3,2014-09-03,0,0,1,1,0,1
348604,28,2,2014-09-02,0,0,1,1,0,1
386065,102,4,2014-07-24,0,0,1,0,0,1
386173,238,4,2014-07-24,0,0,1,0,0,1
386227,303,4,2014-07-24,0,0,1,0,0,1
386304,387,4,2014-07-24,0,0,1,0,0,1
387652,882,3,2014-07-23,0,0,1,0,0,1
387656,887,3,2014-07-23,0,0,1,0,0,0
397285,102,6,2014-07-12,0,0,1,0,0,0
406384,925,4,2014-07-03,0,0,1,1,0,0

In [21]:
train["Sales"].describe()

count    1.017209e+06
mean     5.773819e+03
std      3.849926e+03
min      0.000000e+00
25%      3.727000e+03
50%      5.744000e+03
75%      7.856000e+03
max      4.155100e+04
Name: Sales, dtype: float64

In [22]:
train[train["Open"] == 1]["Sales"].describe()

count    844392.000000
mean       6955.514291
std        3104.214680
min           0.000000
25%        4859.000000
50%        6369.000000
75%        8360.000000
max       41551.000000
Name: Sales, dtype: float64

In [23]:
train.isna().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [24]:
df_store.isna().sum()

Store                          0
StoreType                      0
Assortment                     0
CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
Promo2                         0
Promo2SinceWeek              544
Promo2SinceYear              544
PromoInterval                544
dtype: int64

In [25]:
df_store

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1110,1111,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1111,1112,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1112,1113,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1113,1114,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1114,1115,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [26]:
df_store[df_store["Promo2SinceWeek"].isna()][["Store", "Promo2"]].head()

   Store  Promo2
0      1       0
3      4       0
4      5       0
5      6       0
6      7       0

In [27]:
df_store[df_store["CompetitionOpenSinceMonth"].isna()][
    ["Store", "CompetitionOpenSinceMonth", "CompetitionOpenSinceYear"]
].head()

    Store  CompetitionOpenSinceMonth  CompetitionOpenSinceYear
11     12                        NaN                       NaN
12     13                        NaN                       NaN
15     16                        NaN                       NaN
18     19                        NaN                       NaN
21     22                        NaN                       NaN

In [28]:
df_store[df_store["CompetitionDistance"].isna()]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
290,291,d,a,NaN,NaN,NaN,0,NaN,NaN,NaN
621,622,a,c,NaN,NaN,NaN,0,NaN,NaN,NaN
878,879,d,a,NaN,NaN,NaN,1,5.0,2013.0,"Feb,May,Aug,Nov"

In [29]:
df_store[df_store["CompetitionDistance"].isna()][
    ["Store", "StoreType", "Assortment", "CompetitionDistance",
     "CompetitionOpenSinceMonth", "CompetitionOpenSinceYear"]
]

,Store,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear
290,291,d,a,NaN,NaN,NaN
621,622,a,c,NaN,NaN,NaN
878,879,d,a,NaN,NaN,NaN

In [30]:
df_store["StoreType"].value_counts()

StoreType
a    602
d    348
c    148
b     17
Name: count, dtype: int64

In [31]:
df_store["StoreType"].value_counts(normalize=True) * 100

StoreType
a    53.991031
d    31.210762
c    13.273543
b     1.524664
Name: proportion, dtype: float64

In [32]:
df_store["Assortment"].value_counts(normalize=True) * 100

Assortment
a    53.183857
c    46.008969
b     0.807175
Name: proportion, dtype: float64

In [33]:
df_store["Promo2"].value_counts()

Promo2
1    571
0    544
Name: count, dtype: int64

In [34]:
df_store["PromoInterval"].value_counts(dropna=False)

PromoInterval
NaN                 544
Jan,Apr,Jul,Oct     335
Feb,May,Aug,Nov     130
Mar,Jun,Sept,Dec    106
Name: count, dtype: int64

In [35]:
df_store.groupby("Promo2")["PromoInterval"].apply(lambda x: x.notna().sum())

Promo2
0      0
1    571
Name: PromoInterval, dtype: int64

In [36]:
df_store.groupby("Promo2")[["Promo2SinceWeek", "Promo2SinceYear"]].apply(
    lambda x: x.notna().sum()
)

        Promo2SinceWeek  Promo2SinceYear
Promo2
0                     0                0
1                   571              571

In [37]:
df_store[
    ["CompetitionDistance",
     "CompetitionOpenSinceMonth",
     "CompetitionOpenSinceYear"]
].isna().sum()

CompetitionDistance            3
CompetitionOpenSinceMonth    354
CompetitionOpenSinceYear     354
dtype: int64

In [38]:
df_store[
    df_store["CompetitionDistance"].isna()
][
    ["Store",
     "CompetitionDistance",
     "CompetitionOpenSinceMonth",
     "CompetitionOpenSinceYear"]
]

,Store,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear
290,291,NaN,NaN,NaN
621,622,NaN,NaN,NaN
878,879,NaN,NaN,NaN

In [39]:
train["DayOfWeek"].value_counts().sort_index()

DayOfWeek
1    144730
2    145664
3    145665
4    145845
5    145845
6    144730
7    144730
Name: count, dtype: int64

In [40]:
train["Promo"].value_counts()

Promo
0    629129
1    388080
Name: count, dtype: int64

In [41]:
train["StateHoliday"].value_counts(dropna=False)

StateHoliday
0    855087
0    131072
a     20260
b      6690
c      4100
Name: count, dtype: int64

In [42]:
train["StateHoliday"].map(lambda x: (x, type(x))).value_counts()

StateHoliday
(0, <class 'str'>)    855087
(0, <class 'int'>)    131072
(a, <class 'str'>)     20260
(b, <class 'str'>)      6690
(c, <class 'str'>)      4100
Name: count, dtype: int64

In [43]:
train["StateHoliday"] = train["StateHoliday"].astype(str)

In [44]:
df_test["StateHoliday"].map(lambda x: (x, type(x))).value_counts()

StateHoliday
(0, <class 'str'>)    40908
(a, <class 'str'>)      180
Name: count, dtype: int64

In [45]:
train["StateHoliday"] = train["StateHoliday"].astype(str)

In [46]:
train["SchoolHoliday"].value_counts()

SchoolHoliday
0    835488
1    181721
Name: count, dtype: int64

In [47]:
df_test["SchoolHoliday"].value_counts()

SchoolHoliday
0    22866
1    18222
Name: count, dtype: int64

In [48]:
train.isna().sum()

Store            0
DayOfWeek        0
Date             0
Sales            0
Customers        0
Open             0
Promo            0
StateHoliday     0
SchoolHoliday    0
dtype: int64

In [49]:
train["StateHoliday"] = train["StateHoliday"].astype(str)

In [50]:
train["StateHoliday"].map(lambda x: (x, type(x))).value_counts()

StateHoliday
(0, <class 'str'>)    986159
(a, <class 'str'>)     20260
(b, <class 'str'>)      6690
(c, <class 'str'>)      4100
Name: count, dtype: int64

In [51]:
df_test["StateHoliday"] = df_test["StateHoliday"].astype(str)

In [52]:
print("Train:", train["StateHoliday"].unique())
print("Test :", df_test["StateHoliday"].unique())

Train: ['0' 'a' 'b' 'c']
Test : ['0' 'a']

In [53]:
df_store["Store"].nunique(), len(df_store)

(1115, 1115)

In [54]:
train = train.merge(
    df_store,
    on="Store",
    how="left",
    validate="many_to_one"
)

In [55]:
train.shape

(1017209, 18)

In [56]:
train.isna().sum()

Store                             0
DayOfWeek                         0
Date                              0
Sales                             0
Customers                         0
Open                              0
Promo                             0
StateHoliday                      0
SchoolHoliday                     0
StoreType                         0
Assortment                        0
CompetitionDistance            2642
CompetitionOpenSinceMonth    323348
CompetitionOpenSinceYear     323348
Promo2                            0
Promo2SinceWeek              508031
Promo2SinceYear              508031
PromoInterval                508031
dtype: int64

In [57]:
train

,Store,DayOfWeek,Date,Sales,Customers,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment,CompetitionDistance,CompetitionOpenSinceMonth,CompetitionOpenSinceYear,Promo2,Promo2SinceWeek,Promo2SinceYear,PromoInterval
0,1,5,2015-07-31,5263,555,1,1,0,1,c,a,1270.0,9.0,2008.0,0,NaN,NaN,NaN
1,2,5,2015-07-31,6064,625,1,1,0,1,a,a,570.0,11.0,2007.0,1,13.0,2010.0,"Jan,Apr,Jul,Oct"
2,3,5,2015-07-31,8314,821,1,1,0,1,a,a,14130.0,12.0,2006.0,1,14.0,2011.0,"Jan,Apr,Jul,Oct"
3,4,5,2015-07-31,13995,1498,1,1,0,1,c,c,620.0,9.0,2009.0,0,NaN,NaN,NaN
4,5,5,2015-07-31,4822,559,1,1,0,1,a,a,29910.0,4.0,2015.0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017204,1111,2,2013-01-01,0,0,0,0,a,1,a,a,1900.0,6.0,2014.0,1,31.0,2013.0,"Jan,Apr,Jul,Oct"
1017205,1112,2,2013-01-01,0,0,0,0,a,1,c,c,1880.0,4.0,2006.0,0,NaN,NaN,NaN
1017206,1113,2,2013-01-01,0,0,0,0,a,1,a,c,9260.0,NaN,NaN,0,NaN,NaN,NaN
1017207,1114,2,2013-01-01,0,0,0,0,a,1,a,c,870.0,NaN,NaN,0,NaN,NaN,NaN
1017208,1115,2,2013-01-01,0,0,0,0,a,1,d,c,5350.0,NaN,NaN,1,22.0,2012.0,"Mar,Jun,Sept,Dec"

In [58]:
train["StoreType"].isna().sum()

np.int64(0)

In [59]:
df_test = df_test.merge(
    df_store,
    on="Store",
    how="left",
    validate="many_to_one"
)

In [60]:
df_test.shape

(41088, 17)

In [61]:
df_test["StoreType"].isna().sum()

np.int64(0)

In [62]:
print("Train columns:")
print(train.columns.tolist())

print("\nTest columns:")
print(df_test.columns.tolist())

Train columns:
['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']

Test columns:
['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval']

In [63]:
set(train.columns) - set(df_test.columns)

{'Customers', 'Sales'}

In [64]:
print("Customers in train:", "Customers" in train.columns)
print("Customers in test :", "Customers" in df_test.columns)

Customers in train: True
Customers in test : False

In [65]:
train[["Customers", "Sales"]].corr()

           Customers     Sales
Customers   1.000000  0.894711
Sales       0.894711  1.000000

In [66]:
df_sample["Sales"].value_counts()

Sales
0    41088
Name: count, dtype: int64

In [67]:
pd.crosstab(
    train["Open"],
    train["Sales"].eq(0)
)

Sales   False   True
Open
0           0  172817
1      844338      54

In [68]:
train.groupby("DayOfWeek")["Sales"].agg(
    ["count", "mean", "median", "min", "max"]
)

            count         mean  median  min    max
DayOfWeek
1          144730  7809.044510  7310.0    0  41551
2          145664  7005.244467  6463.0    0  34692
3          145665  6555.884138  6133.0    0  33151
4          145845  6247.575913  6020.0    0  38367
5          145845  6723.274305  6434.0    0  38722
6          144730  5847.562599  5410.0    0  31683
7          144730   204.183189     0.0    0  37376

In [69]:
train.groupby("DayOfWeek")["Open"].mean()

DayOfWeek
1    0.950459
2    0.988309
3    0.974400
4    0.923199
5    0.950598
6    0.995357
7    0.024826
Name: Open, dtype: float64

In [70]:
train.groupby("Open")["Customers"].agg(
    ["count", "mean", "median", "min", "max"]
)

       count        mean  median  min   max
Open
0     172817    0.000000     0.0    0     0
1     844392  762.728395   676.0    0  7388

In [71]:
train = train.sort_values(["Date", "Store"]).reset_index(drop=True)
df_test = df_test.sort_values(["Date", "Store"]).reset_index(drop=True)

In [72]:
print(train["Date"].min(), train["Date"].max())
print(df_test["Date"].min(), df_test["Date"].max())

2013-01-01 00:00:00 2015-07-31 00:00:00
2015-08-01 2015-09-17

In [73]:
train["Date"] = pd.to_datetime(train["Date"])
df_test["Date"] = pd.to_datetime(df_test["Date"])

In [74]:
print(train["Date"].dtype)
print(df_test["Date"].dtype)

datetime64[ns]
datetime64[ns]

In [75]:
for df in [train, df_test]:
    df["Year"] = df["Date"].dt.year
    df["Month"] = df["Date"].dt.month
    df["Day"] = df["Date"].dt.day
    df["WeekOfYear"] = df["Date"].dt.isocalendar().week.astype(int)

In [76]:
train[["Date", "Year", "Month", "Day", "WeekOfYear"]].head(10)

        Date  Year  Month  Day  WeekOfYear
0 2013-01-01  2013      1    1           1
1 2013-01-01  2013      1    1           1
2 2013-01-01  2013      1    1           1
3 2013-01-01  2013      1    1           1
4 2013-01-01  2013      1    1           1
5 2013-01-01  2013      1    1           1
6 2013-01-01  2013      1    1           1
7 2013-01-01  2013      1    1           1
8 2013-01-01  2013      1    1           1
9 2013-01-01  2013      1    1           1

In [77]:
print("Train columns:")
print(train.columns.tolist())

print("\nTest columns:")
print(df_test.columns.tolist())

Train columns:
['Store', 'DayOfWeek', 'Date', 'Sales', 'Customers', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month', 'Day', 'WeekOfYear']

Test columns:
['Id', 'Store', 'DayOfWeek', 'Date', 'Open', 'Promo', 'StateHoliday', 'SchoolHoliday', 'StoreType', 'Assortment', 'CompetitionDistance', 'CompetitionOpenSinceMonth', 'CompetitionOpenSinceYear', 'Promo2', 'Promo2SinceWeek', 'Promo2SinceYear', 'PromoInterval', 'Year', 'Month', 'Day', 'WeekOfYear']

In [78]:
print("Year:", train["Year"].unique())
print("Month:", sorted(train["Month"].unique()))
print("Day:", sorted(train["Day"].unique()))
print("WeekOfYear:", train["WeekOfYear"].min(), train["WeekOfYear"].max())

Year: [2013 2014 2015]
Month: [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12)]
Day: [np.int32(1), np.int32(2), np.int32(3), np.int32(4), np.int32(5), np.int32(6), np.int32(7), np.int32(8), np.int32(9), np.int32(10), np.int32(11), np.int32(12), np.int32(13), np.int32(14), np.int32(15), np.int32(16), np.int32(17), np.int32(18), np.int32(19), np.int32(20), np.int32(21), np.int32(22), np.int32(23), np.int32(24), np.int32(25), np.int32(26), np.int32(27), np.int32(28), np.int32(29), np.int32(30), np.int32(31)]
WeekOfYear: 1 52

In [79]:
print("Minimum date:", train["Date"].min())
print("Maximum date:", train["Date"].max())

Minimum date: 2013-01-01 00:00:00
Maximum date: 2015-07-31 00:00:00

In [80]:
validation_start = train["Date"].max() - pd.Timedelta(weeks=6)

print("Validation starts:", validation_start)

Validation starts: 2015-06-19 00:00:00

In [81]:
train_data = train[train["Date"] < validation_start].copy()
validation_data = train[train["Date"] >= validation_start].copy()

In [82]:
print("Training period:")
print(train_data["Date"].min(), "to", train_data["Date"].max())

print("\nValidation period:")
print(validation_data["Date"].min(), "to", validation_data["Date"].max())

print("\nRows:")
print("Training:", len(train_data))
print("Validation:", len(validation_data))

Training period:
2013-01-01 00:00:00 to 2015-06-18 00:00:00

Validation period:
2015-06-19 00:00:00 to 2015-07-31 00:00:00

Rows:
Training: 969264
Validation: 47945

In [83]:
train_data["Date"].max() < validation_data["Date"].min()

True

In [84]:
target = "Sales"

feature_columns = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "StateHoliday",
    "SchoolHoliday",
    "StoreType",
    "Assortment",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "PromoInterval",
    "Year",
    "Month",
    "Day",
    "WeekOfYear"
]

In [85]:
X_train = train_data[feature_columns].copy()
y_train = train_data[target].copy()

X_validation = validation_data[feature_columns].copy()
y_validation = validation_data[target].copy()

In [86]:
print("X_train:", X_train.shape)
print("y_train:", y_train.shape)

print("X_validation:", X_validation.shape)
print("y_validation:", y_validation.shape)

X_train: (969264, 19)
y_train: (969264,)
X_validation: (47945, 19)
y_validation: (47945,)

In [87]:
print("Customers" in feature_columns)
print("Sales" in feature_columns)
print("Date" in feature_columns)

False
False
False

In [88]:
categorical_columns = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

for column in categorical_columns:
    print(f"\n{column}")
    print("Data type:", X_train[column].dtype)
    print("Unique values:", X_train[column].dropna().unique())

StateHoliday
Data type: object
Unique values: ['a' '0' 'b' 'c']

StoreType
Data type: object
Unique values: ['c' 'a' 'd' 'b']

Assortment
Data type: object
Unique values: ['a' 'c' 'b']

PromoInterval
Data type: object
Unique values: ['Jan,Apr,Jul,Oct' 'Feb,May,Aug,Nov' 'Mar,Jun,Sept,Dec']

In [89]:
X_train.dtypes

Store                          int64
DayOfWeek                      int64
Open                           int64
Promo                          int64
StateHoliday                  object
SchoolHoliday                  int64
StoreType                     object
Assortment                    object
CompetitionDistance          float64
CompetitionOpenSinceMonth    float64
CompetitionOpenSinceYear     float64
Promo2                         int64
Promo2SinceWeek              float64
Promo2SinceYear              float64
PromoInterval                 object
Year                           int32
Month                          int32
Day                            int32
WeekOfYear                     int64
dtype: object

In [90]:
categorical_columns = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

numerical_columns = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "SchoolHoliday",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "Year",
    "Month",
    "Day",
    "WeekOfYear"
]

In [91]:
print("Total feature columns:", len(feature_columns))
print("Categorical columns:", len(categorical_columns))
print("Numerical columns:", len(numerical_columns))
print("Combined columns:", len(categorical_columns) + len(numerical_columns))

Total feature columns: 19
Categorical columns: 4
Numerical columns: 15
Combined columns: 19

In [92]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [93]:
numerical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

In [94]:
categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

In [95]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numerical_transformer, numerical_columns),
        ("cat", categorical_transformer, categorical_columns)
    ]
)

In [96]:
X_train_processed = preprocessor.fit_transform(X_train)
X_validation_processed = preprocessor.transform(X_validation)

print("Processed training shape:", X_train_processed.shape)
print("Processed validation shape:", X_validation_processed.shape)

Processed training shape: (969264, 29)
Processed validation shape: (47945, 29)

In [97]:
print("Training rows:", X_train.shape[0])
print("Processed training rows:", X_train_processed.shape[0])

print("Validation rows:", X_validation.shape[0])
print("Processed validation rows:", X_validation_processed.shape[0])

print("Feature count before encoding:", X_train.shape[1])
print("Feature count after encoding:", X_train_processed.shape[1])

Training rows: 969264
Processed training rows: 969264
Validation rows: 47945
Processed validation rows: 47945
Feature count before encoding: 19
Feature count after encoding: 29

In [98]:
feature_names = preprocessor.get_feature_names_out()

print(feature_names)
print("Total encoded features:", len(feature_names))

['num__Store' 'num__DayOfWeek' 'num__Open' 'num__Promo'
 'num__SchoolHoliday' 'num__CompetitionDistance'
 'num__CompetitionOpenSinceMonth' 'num__CompetitionOpenSinceYear'
 'num__Promo2' 'num__Promo2SinceWeek' 'num__Promo2SinceYear' 'num__Year'
 'num__Month' 'num__Day' 'num__WeekOfYear' 'cat__StateHoliday_0'
 'cat__StateHoliday_a' 'cat__StateHoliday_b' 'cat__StateHoliday_c'
 'cat__StoreType_a' 'cat__StoreType_b' 'cat__StoreType_c'
 'cat__StoreType_d' 'cat__Assortment_a' 'cat__Assortment_b'
 'cat__Assortment_c' 'cat__PromoInterval_Feb,May,Aug,Nov'
 'cat__PromoInterval_Jan,Apr,Jul,Oct'
 'cat__PromoInterval_Mar,Jun,Sept,Dec']
Total encoded features: 29

In [99]:
from sklearn.linear_model import LinearRegression

In [100]:
baseline_model = LinearRegression()

baseline_model.fit(X_train_processed, y_train)

LinearRegression()

In [101]:
y_validation_pred = baseline_model.predict(X_validation_processed)

In [102]:
comparison = pd.DataFrame({
    "Actual": y_validation.values[:10],
    "Predicted": y_validation_pred[:10]
})

comparison

   Actual    Predicted
0    4202  8019.146770
1    4926  7445.979821
2    8074  7125.188693
3    9686  8760.807085
4    5711  7651.192466
5    5464  8014.669970
6    9677  8498.157359
7    6773  7928.068663
8    7849  8818.839755
9    6191  8043.765554

In [103]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
mae = mean_absolute_error(y_validation, y_validation_pred)

rmse = np.sqrt(
    mean_squared_error(y_validation, y_validation_pred)
)

r2 = r2_score(y_validation, y_validation_pred)

print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 1746.3773235431142
RMSE: 2458.0730677080296
R²: 0.5612497062440193

In [104]:
store_mean_sales = (
    train_data.groupby("Store")["Sales"]
    .mean()
)

In [105]:
store_mean_predictions = validation_data["Store"].map(store_mean_sales)

In [106]:
print("Missing baseline predictions:", store_mean_predictions.isna().sum())

Missing baseline predictions: 0

In [107]:
store_mean_mae = mean_absolute_error(
    y_validation,
    store_mean_predictions
)

store_mean_rmse = np.sqrt(
    mean_squared_error(
        y_validation,
        store_mean_predictions
    )
)

store_mean_r2 = r2_score(
    y_validation,
    store_mean_predictions
)

print("Store-mean MAE:", store_mean_mae)
print("Store-mean RMSE:", store_mean_rmse)
print("Store-mean R²:", store_mean_r2)

Store-mean MAE: 2202.843952918167
Store-mean RMSE: 3082.312004598822
Store-mean R²: 0.31010811121681525

In [108]:
sample_fraction = 0.20

train_sample = (
    train_data
    .groupby(train_data["Date"].dt.to_period("M"), group_keys=False)
    .sample(frac=sample_fraction, random_state=42)
    .sort_values(["Date", "Store"])
)

print("Original training rows:", len(train_data))
print("Sampled training rows:", len(train_sample))

Original training rows: 969264
Sampled training rows: 193853

In [109]:
X_train_sample = train_sample[feature_columns].copy()
y_train_sample = train_sample["Sales"].copy()

print("X_train_sample:", X_train_sample.shape)
print("y_train_sample:", y_train_sample.shape)

X_train_sample: (193853, 19)
y_train_sample: (193853,)

In [110]:
X_train_sample_processed = preprocessor.transform(X_train_sample)

print("Processed sample shape:", X_train_sample_processed.shape)

Processed sample shape: (193853, 29)

In [111]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(
    n_estimators=30,
    max_depth=15,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

In [112]:
rf_model.fit(
    X_train_sample_processed,
    y_train_sample
)

RandomForestRegressor(max_depth=15, min_samples_leaf=10, n_estimators=30,
                      n_jobs=-1, random_state=42)

In [113]:
rf_validation_pred = rf_model.predict(
    X_validation_processed
)
print("Minimum prediction:", rf_validation_pred.min())
print("Maximum prediction:", rf_validation_pred.max())
rf_mae = mean_absolute_error(
    y_validation,
    rf_validation_pred
)

rf_rmse = np.sqrt(
    mean_squared_error(
        y_validation,
        rf_validation_pred
    )
)

rf_r2 = r2_score(
    y_validation,
    rf_validation_pred
)

print("Random Forest MAE:", rf_mae)
print("Random Forest RMSE:", rf_rmse)
print("Random Forest R²:", rf_r2)

Minimum prediction: 0.0
Maximum prediction: 29165.25422113363
Random Forest MAE: 1125.1263453740223
Random Forest RMSE: 1720.2877763045262
Random Forest R²: 0.7851031496478647

In [114]:
comparison_rf = pd.DataFrame({
    "Actual": y_validation.to_numpy(),
    "Predicted": rf_validation_pred
})

comparison_rf["Error"] = (
    comparison_rf["Predicted"] - comparison_rf["Actual"]
)

comparison_rf["AbsoluteError"] = (
    comparison_rf["Error"].abs()
)

comparison_rf.head(20)

    Actual    Predicted        Error  AbsoluteError
0     4202  6777.188878  2575.188878    2575.188878
1     4926  6420.162639  1494.162639    1494.162639
2     8074  7919.497976  -154.502024     154.502024
3     9686  7641.678099 -2044.321901    2044.321901
4     5711  5505.998603  -205.001397     205.001397
5     5464  5911.980422   447.980422     447.980422
6     9677  7524.877048 -2152.122952    2152.122952
7     6773  6627.559771  -145.440229     145.440229
8     7849  7277.288986  -571.711014     571.711014
9     6191  6611.199179   420.199179     420.199179
10    6592  7106.567461   514.567461     514.567461
11    8836  7932.843561  -903.156439     903.156439
12    5546  6825.118430  1279.118430    1279.118430
13    6239  6615.899669   376.899669     376.899669
14    7851  7781.134105   -69.865895      69.865895
15    8580  7447.112581 -1132.887419    1132.887419
16    6820  7411.827115   591.827115     591.827115
17    8270  7114.173349 -1155.826651    1155.826651
18    8508  7244.420843 -1263.579157    1263.579157
19    8505  7918.008714  -586.991286     586.991286

In [115]:
largest_errors = comparison_rf.sort_values(
    "AbsoluteError",
    ascending=False
)

largest_errors.head(10)

       Actual     Predicted         Error  AbsoluteError
4253    41551   6628.146376 -34922.853624   34922.853624
5368    30038   6628.146376 -23409.853624   23409.853624
19830   27330   5579.958764 -21750.041236   21750.041236
11441   29161   9445.269931 -19715.730069   19715.730069
20945   23927   5579.958764 -18347.041236   18347.041236
43211   27881  11128.922728 -16752.077272   16752.077272
35473   23081   6628.146376 -16452.853624   16452.853624
2023    22882   6624.726398 -16257.273602   16257.273602
12556   23584   7341.926004 -16242.073996   16242.073996
1956    23978   7736.223880 -16241.776120   16241.776120

In [116]:
largest_indices = comparison_rf.sort_values(
    "AbsoluteError",
    ascending=False
).head(10).index

In [117]:
error_rows = validation_data.iloc[largest_indices].copy()

error_rows[
    [
        "Date",
        "Store",
        "DayOfWeek",
        "Sales",
        "Open",
        "Promo",
        "StateHoliday",
        "SchoolHoliday",
        "StoreType",
        "Assortment"
    ]
]

,Date,Store,DayOfWeek,Sales,Open,Promo,StateHoliday,SchoolHoliday,StoreType,Assortment
973517,2015-06-22,909,1,41551,1,0,0,0,a,c
974632,2015-06-23,909,2,30038,1,0,0,0,a,c
989094,2015-07-06,876,1,27330,1,0,0,0,a,a
980705,2015-06-29,292,1,29161,1,1,0,0,a,a
990209,2015-07-07,876,2,23927,1,0,0,0,a,a
1012475,2015-07-27,842,1,27881,1,1,0,0,d,c
1004737,2015-07-20,909,1,23081,1,0,0,0,a,c
971287,2015-06-20,909,6,22882,1,0,0,0,a,c
981820,2015-06-30,292,2,23584,1,1,0,0,a,a
971220,2015-06-20,842,6,23978,1,0,0,0,d,c

In [118]:
train["Sales"].shift(1).rolling(7).mean()

0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
              ...
1017204    6895.571429
1017205    6730.571429
1017206    6963.714286
1017207    7162.000000
1017208    9744.142857
Name: Sales, Length: 1017209, dtype: float64

In [119]:
train_features = train.copy()
test_features = df_test.copy()

In [120]:
print(train_features[["Store", "Date", "Sales"]].head())
print(test_features[["Store", "Date"]].head())

   Store       Date  Sales
0      1 2013-01-01      0
1      2 2013-01-01      0
2      3 2013-01-01      0
3      4 2013-01-01      0
4      5 2013-01-01      0
   Store       Date
0      1 2015-08-01
1      3 2015-08-01
2      7 2015-08-01
3      8 2015-08-01
4      9 2015-08-01

In [121]:
train_features["Sales_Lag_1"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(1)
)

train_features["Sales_Lag_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(7)
)

In [122]:
train_features["Sales_Rolling_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .transform(
        lambda x: x.shift(1).rolling(7, min_periods=1).mean()
    )
)

In [123]:
train_features[
    [
        "Store",
        "Date",
        "Sales",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(20)

    Store       Date  Sales  Sales_Lag_1  Sales_Lag_7  Sales_Rolling_7
0       1 2013-01-01      0          NaN          NaN              NaN
1       2 2013-01-01      0          NaN          NaN              NaN
2       3 2013-01-01      0          NaN          NaN              NaN
3       4 2013-01-01      0          NaN          NaN              NaN
4       5 2013-01-01      0          NaN          NaN              NaN
5       6 2013-01-01      0          NaN          NaN              NaN
6       7 2013-01-01      0          NaN          NaN              NaN
7       8 2013-01-01      0          NaN          NaN              NaN
8       9 2013-01-01      0          NaN          NaN              NaN
9      10 2013-01-01      0          NaN          NaN              NaN
10     11 2013-01-01      0          NaN          NaN              NaN
11     12 2013-01-01      0          NaN          NaN              NaN
12     13 2013-01-01      0          NaN          NaN              NaN
13     14 2013-01-01      0          NaN          NaN              NaN
14     15 2013-01-01      0          NaN          NaN              NaN
15     16 2013-01-01      0          NaN          NaN              NaN
16     17 2013-01-01      0          NaN          NaN              NaN
17     18 2013-01-01      0          NaN          NaN              NaN
18     19 2013-01-01      0          NaN          NaN              NaN
19     20 2013-01-01      0          NaN          NaN              NaN

In [124]:
train_features[
    train_features["Store"] == 1
][
    [
        "Store",
        "Date",
        "Sales",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(15)

       Store       Date  Sales  Sales_Lag_1  Sales_Lag_7  Sales_Rolling_7
0          1 2013-01-01      0          NaN          NaN              NaN
1114       1 2013-01-02   5530          0.0          NaN         0.000000
2229       1 2013-01-03   4327       5530.0          NaN      2765.000000
3344       1 2013-01-04   4486       4327.0          NaN      3285.666667
4459       1 2013-01-05   4997       4486.0          NaN      3585.750000
5574       1 2013-01-06      0       4997.0          NaN      3868.000000
6689       1 2013-01-07   7176          0.0          NaN      3223.333333
7804       1 2013-01-08   5580       7176.0          0.0      3788.000000
8919       1 2013-01-09   5471       5580.0       5530.0      4585.142857
10034      1 2013-01-10   4892       5471.0       4327.0      4576.714286
11149      1 2013-01-11   4881       4892.0       4486.0      4657.428571
12264      1 2013-01-12   4952       4881.0       4997.0      4713.857143
13379      1 2013-01-13      0       4952.0          0.0      4707.428571
14494      1 2013-01-14   4717          0.0       7176.0      4707.428571
15609      1 2013-01-15   3900       4717.0       5580.0      4356.142857

In [125]:
print(
    train_features[
        ["Sales_Lag_1", "Sales_Lag_7", "Sales_Rolling_7"]
    ].isna().sum()
)

Sales_Lag_1        1115
Sales_Lag_7        7805
Sales_Rolling_7    1115
dtype: int64

In [126]:
train_features[
    train_features["Store"] == 1
][
    [
        "Store",
        "Date",
        "Sales",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(15)

       Store       Date  Sales  Sales_Lag_1  Sales_Lag_7  Sales_Rolling_7
0          1 2013-01-01      0          NaN          NaN              NaN
1114       1 2013-01-02   5530          0.0          NaN         0.000000
2229       1 2013-01-03   4327       5530.0          NaN      2765.000000
3344       1 2013-01-04   4486       4327.0          NaN      3285.666667
4459       1 2013-01-05   4997       4486.0          NaN      3585.750000
5574       1 2013-01-06      0       4997.0          NaN      3868.000000
6689       1 2013-01-07   7176          0.0          NaN      3223.333333
7804       1 2013-01-08   5580       7176.0          0.0      3788.000000
8919       1 2013-01-09   5471       5580.0       5530.0      4585.142857
10034      1 2013-01-10   4892       5471.0       4327.0      4576.714286
11149      1 2013-01-11   4881       4892.0       4486.0      4657.428571
12264      1 2013-01-12   4952       4881.0       4997.0      4713.857143
13379      1 2013-01-13      0       4952.0          0.0      4707.428571
14494      1 2013-01-14   4717          0.0       7176.0      4707.428571
15609      1 2013-01-15   3900       4717.0       5580.0      4356.142857

In [127]:
print("Test minimum date:", test_features["Date"].min())
print("Test maximum date:", test_features["Date"].max())

Test minimum date: 2015-08-01 00:00:00
Test maximum date: 2015-09-17 00:00:00

In [128]:
# Check the final historical dates for selected stores
boundary_check = (
    train_features[
        train_features["Date"] >= "2015-07-24"
    ][
        ["Store", "Date", "Sales"]
    ]
    .sort_values(["Store", "Date"])
)

boundary_check.head(20)

         Store       Date  Sales
1008289      1 2015-07-24   3706
1009404      1 2015-07-25   4364
1010519      1 2015-07-26      0
1011634      1 2015-07-27   6102
1012749      1 2015-07-28   5011
1013864      1 2015-07-29   4782
1014979      1 2015-07-30   5020
1016094      1 2015-07-31   5263
1008290      2 2015-07-24   3854
1009405      2 2015-07-25   2512
1010520      2 2015-07-26      0
1011635      2 2015-07-27   6627
1012750      2 2015-07-28   5671
1013865      2 2015-07-29   6402
1014980      2 2015-07-30   5567
1016095      2 2015-07-31   6064
1008291      3 2015-07-24   5080
1009406      3 2015-07-25   3878
1010521      3 2015-07-26      0
1011636      3 2015-07-27   8107

In [129]:
store_1_history = (
    train_features[
        (train_features["Store"] == 1) &
        (train_features["Date"] >= "2015-07-25")
    ][
        ["Store", "Date", "Sales"]
    ]
    .sort_values("Date")
)

store_1_history

         Store       Date  Sales
1009404      1 2015-07-25   4364
1010519      1 2015-07-26      0
1011634      1 2015-07-27   6102
1012749      1 2015-07-28   5011
1013864      1 2015-07-29   4782
1014979      1 2015-07-30   5020
1016094      1 2015-07-31   5263

In [130]:
store_1_history = (
    train_features[
        (train_features["Store"] == 1) &
        (train_features["Date"] >= "2015-07-25")
    ][["Store", "Date", "Sales"]]
    .sort_values("Date")
)

store_1_history["Sales_Lag_1"] = store_1_history["Sales"].shift(1)
store_1_history["Sales_Lag_7"] = store_1_history["Sales"].shift(7)
store_1_history["Sales_Rolling_7"] = (
    store_1_history["Sales"]
    .shift(1)
    .rolling(7, min_periods=1)
    .mean()
)

store_1_history

         Store       Date  Sales  Sales_Lag_1  Sales_Lag_7  Sales_Rolling_7
1009404      1 2015-07-25   4364          NaN          NaN              NaN
1010519      1 2015-07-26      0       4364.0          NaN      4364.000000
1011634      1 2015-07-27   6102          0.0          NaN      2182.000000
1012749      1 2015-07-28   5011       6102.0          NaN      3488.666667
1013864      1 2015-07-29   4782       5011.0          NaN      3869.250000
1014979      1 2015-07-30   5020       4782.0          NaN      4051.800000
1016094      1 2015-07-31   5263       5020.0          NaN      4213.166667

In [131]:
store_1_history = (
    train_features[
        (train_features["Store"] == 1) &
        (train_features["Date"] >= "2015-07-24") &
        (train_features["Date"] <= "2015-07-31")
    ][["Store", "Date", "Sales"]]
    .sort_values("Date")
)

store_1_history["Sales_Lag_1"] = (
    store_1_history["Sales"].shift(1)
)

store_1_history["Sales_Lag_7"] = (
    store_1_history["Sales"].shift(7)
)

store_1_history["Sales_Rolling_7"] = (
    store_1_history["Sales"]
    .shift(1)
    .rolling(7, min_periods=1)
    .mean()
)

store_1_history

         Store       Date  Sales  Sales_Lag_1  Sales_Lag_7  Sales_Rolling_7
1008289      1 2015-07-24   3706          NaN          NaN              NaN
1009404      1 2015-07-25   4364       3706.0          NaN      3706.000000
1010519      1 2015-07-26      0       4364.0          NaN      4035.000000
1011634      1 2015-07-27   6102          0.0          NaN      2690.000000
1012749      1 2015-07-28   5011       6102.0          NaN      3543.000000
1013864      1 2015-07-29   4782       5011.0          NaN      3836.600000
1014979      1 2015-07-30   5020       4782.0          NaN      3994.166667
1016094      1 2015-07-31   5263       5020.0       3706.0      4140.714286

In [132]:
# Prepare the first test date
first_test_date = test_features["Date"].min()

first_test_day = test_features[
    test_features["Date"] == first_test_date
].copy()

# Historical sales indexed by Store and Date
historical_sales = (
    train_features
    .set_index(["Store", "Date"])["Sales"]
)

# Calculate lag features for the first test date
first_test_day["Sales_Lag_1"] = first_test_day.apply(
    lambda row: historical_sales.get(
        (row["Store"], row["Date"] - pd.Timedelta(days=1)),
        np.nan
    ),
    axis=1
)

first_test_day["Sales_Lag_7"] = first_test_day.apply(
    lambda row: historical_sales.get(
        (row["Store"], row["Date"] - pd.Timedelta(days=7)),
        np.nan
    ),
    axis=1
)

def calculate_historical_rolling(row):
    store = row["Store"]
    current_date = row["Date"]

    previous_seven_days = historical_sales.reindex(
        pd.MultiIndex.from_product(
            [[store], pd.date_range(
                current_date - pd.Timedelta(days=7),
                current_date - pd.Timedelta(days=1)
            )],
            names=["Store", "Date"]
        )
    )

    return previous_seven_days.mean()

first_test_day["Sales_Rolling_7"] = first_test_day.apply(
    calculate_historical_rolling,
    axis=1
)

first_test_day[
    [
        "Store",
        "Date",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(10)

KeyboardInterrupt:

In [ ]:
train = train.sort_values(["Date", "Store"]).reset_index(drop=True)
df_test = df_test.sort_values(["Date", "Store"]).reset_index(drop=True)

In [ ]:
train_features["Sales_Lag_1"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(1)
)

train_features["Sales_Lag_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(7)
)

train_features["Sales_Rolling_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .transform(
        lambda x: x.shift(1).rolling(7, min_periods=1).mean()
    )
)

In [ ]:
# Sort by Store first, then Date
train_features = (
    train_features
    .sort_values(["Store", "Date"])
    .reset_index(drop=True)
)

# Calculate lag features separately for each store
train_features["Sales_Lag_1"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(1)
)

train_features["Sales_Lag_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .shift(7)
)

# Rolling average of the previous 7 observations
train_features["Sales_Rolling_7"] = (
    train_features
    .groupby("Store")["Sales"]
    .transform(
        lambda x: x.shift(1).rolling(7, min_periods=1).mean()
    )
)

In [ ]:
train_features[
    train_features["Store"] == 1
][
    [
        "Store",
        "Date",
        "Sales",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(15)

In [ ]:
# Historical sales lookup: Store + Date → Sales
historical_sales = (
    train_features
    .set_index(["Store", "Date"])["Sales"]
)

historical_sales.head()

In [ ]:
def calculate_test_lag_features(row):
    store = row["Store"]
    current_date = row["Date"]

    # Previous day
    lag_1 = historical_sales.get(
        (store, current_date - pd.Timedelta(days=1)),
        np.nan
    )

    # Seven days earlier
    lag_7 = historical_sales.get(
        (store, current_date - pd.Timedelta(days=7)),
        np.nan
    )

    # Previous 7 calendar days
    previous_seven_days = historical_sales.reindex(
        pd.MultiIndex.from_product(
            [
                [store],
                pd.date_range(
                    current_date - pd.Timedelta(days=7),
                    current_date - pd.Timedelta(days=1)
                )
            ],
            names=["Store", "Date"]
        )
    )

    rolling_7 = previous_seven_days.mean()

    return pd.Series({
        "Sales_Lag_1": lag_1,
        "Sales_Lag_7": lag_7,
        "Sales_Rolling_7": rolling_7
    })


test_features[
    ["Sales_Lag_1", "Sales_Lag_7", "Sales_Rolling_7"]
] = test_features.apply(
    calculate_test_lag_features,
    axis=1
)

In [ ]:
test_features[
    [
        "Store",
        "Date",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head(20)

In [ ]:
test_features[
    [
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].isna().sum()

In [ ]:
# Use the same six-week validation boundary
validation_start = train["Date"].max() - pd.Timedelta(weeks=6)

# Historical training and validation sets
train_features_data = train_features[
    train_features["Date"] < validation_start
].copy()

validation_features_data = train_features[
    train_features["Date"] >= validation_start
].copy()

print("Training shape:", train_features_data.shape)
print("Validation shape:", validation_features_data.shape)

In [ ]:
validation_features_data[
    [
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].isna().sum()

In [ ]:
validation_features_data[
    [
        "Store",
        "Date",
        "Sales",
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
].head()

In [ ]:
print("Training missing values:")
print(
    train_features_data[
        [
            "Sales_Lag_1",
            "Sales_Lag_7",
            "Sales_Rolling_7"
        ]
    ].isna().sum()
)

print("\nValidation missing values:")
print(
    validation_features_data[
        [
            "Sales_Lag_1",
            "Sales_Lag_7",
            "Sales_Rolling_7"
        ]
    ].isna().sum()
)

In [ ]:
lag_features = [
    "Sales_Lag_1",
    "Sales_Lag_7",
    "Sales_Rolling_7"
]

feature_columns_with_lags = feature_columns + lag_features

print("Original feature count:", len(feature_columns))
print("New feature count:", len(feature_columns_with_lags))
print("Added features:", lag_features)

In [ ]:
X_train_lag = train_features_data[
    feature_columns_with_lags
].copy()

y_train_lag = train_features_data["Sales"].copy()

X_validation_lag = validation_features_data[
    feature_columns_with_lags
].copy()

y_validation_lag = validation_features_data["Sales"].copy()

print("X_train_lag shape:", X_train_lag.shape)
print("X_validation_lag shape:", X_validation_lag.shape)

In [ ]:
numerical_columns_lag = X_train_lag.select_dtypes(
    include=["number"]
).columns.tolist()

categorical_columns_lag = X_train_lag.select_dtypes(
    exclude=["number"]
).columns.tolist()

print("Numerical columns:")
print(numerical_columns_lag)

print("\nCategorical columns:")
print(categorical_columns_lag)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

numerical_transformer_lag = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

categorical_transformer_lag = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

preprocessor_lag = ColumnTransformer(
    transformers=[
        (
            "num",
            numerical_transformer_lag,
            numerical_columns_lag
        ),
        (
            "cat",
            categorical_transformer_lag,
            categorical_columns_lag
        )
    ]
)

In [ ]:
X_train_lag_processed = preprocessor_lag.fit_transform(X_train_lag)

X_validation_lag_processed = preprocessor_lag.transform(
    X_validation_lag
)

print(
    "Processed training shape:",
    X_train_lag_processed.shape
)

print(
    "Processed validation shape:",
    X_validation_lag_processed.shape
)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Create the model
linear_model_lag = LinearRegression()

# Train
linear_model_lag.fit(
    X_train_lag_processed,
    y_train_lag
)

# Predict validation sales
y_validation_pred_lag = linear_model_lag.predict(
    X_validation_lag_processed
)

# Evaluate
mae_lag = mean_absolute_error(
    y_validation_lag,
    y_validation_pred_lag
)

rmse_lag = np.sqrt(
    mean_squared_error(
        y_validation_lag,
        y_validation_pred_lag
    )
)

r2_lag = r2_score(
    y_validation_lag,
    y_validation_pred_lag
)

print("Linear Regression with lag features")
print("MAE:", mae_lag)
print("RMSE:", rmse_lag)
print("R²:", r2_lag)

In [ ]:
print("Original Linear Regression")
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

print("\nLinear Regression with lag features")
print("MAE:", mae_lag)
print("RMSE:", rmse_lag)
print("R²:", r2_lag)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

random_forest_lag = RandomForestRegressor(
    n_estimators=100,
    max_depth=20,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

random_forest_lag.fit(
    X_train_lag_processed,
    y_train_lag
)

In [ ]:
y_validation_pred_rf_lag = random_forest_lag.predict(
    X_validation_lag_processed
)

In [ ]:
mae_rf_lag = mean_absolute_error(
    y_validation_lag,
    y_validation_pred_rf_lag
)

rmse_rf_lag = np.sqrt(
    mean_squared_error(
        y_validation_lag,
        y_validation_pred_rf_lag
    )
)

r2_rf_lag = r2_score(
    y_validation_lag,
    y_validation_pred_rf_lag
)

print("Random Forest with lag features")
print("MAE:", mae_rf_lag)
print("RMSE:", rmse_rf_lag)
print("R²:", r2_rf_lag)

In [ ]:
print("hi")

In [ ]:
# Check numerical relationships among existing competition and promotion features

check_columns = [
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear"
]

train_features[check_columns].corr()

In [ ]:
competition_cols = [
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear"
]

# Missing values
print("Missing values:")
print(train_features[competition_cols].isna().sum())

# Basic statistics
print("\nSummary statistics:")
display(train_features[competition_cols].describe())

# Unique years and months
print("\nCompetition start years:")
print(sorted(train_features["CompetitionOpenSinceYear"].dropna().unique()))

print("\nCompetition start months:")
print(sorted(train_features["CompetitionOpenSinceMonth"].dropna().unique()))

# Example records
print("\nSample records:")
display(train_features[competition_cols].head(10))

In [ ]:
# Check whether month and year are missing together
month_missing = train_features["CompetitionOpenSinceMonth"].isna()
year_missing = train_features["CompetitionOpenSinceYear"].isna()

print("Both missing:")
print((month_missing & year_missing).sum())

print("\nOnly month missing:")
print((month_missing & ~year_missing).sum())

print("\nOnly year missing:")
print((~month_missing & year_missing).sum())

print("\nNeither missing:")
print((~month_missing & ~year_missing).sum())

# Check stores with the unusual year 1900
print("\nRecords with CompetitionOpenSinceYear = 1900:")
display(
    train_features[
        train_features["CompetitionOpenSinceYear"] == 1900
    ][[
        "Store",
        "Date",
        "CompetitionDistance",
        "CompetitionOpenSinceMonth",
        "CompetitionOpenSinceYear"
    ]].head(20)
)

In [ ]:
store_competition = train_features[
    [
        "Store",
        "CompetitionDistance",
        "CompetitionOpenSinceMonth",
        "CompetitionOpenSinceYear"
    ]
].drop_duplicates()

print("Unique store-level competition records:")
print(store_competition.shape)

print("\nStores with missing competition start date:")
display(
    store_competition[
        store_competition["CompetitionOpenSinceYear"].isna()
    ].head(20)
)

print("\nStores with year 1900:")
display(
    store_competition[
        store_competition["CompetitionOpenSinceYear"] == 1900
    ]
)

print("\nCount of stores with year 1900:")
print(
    (
        store_competition["CompetitionOpenSinceYear"] == 1900
    ).sum()
)

In [ ]:
import numpy as np
import pandas as pd

def add_competition_features(df):
    df = df.copy()

    # Treat year 1900 as an invalid/unknown placeholder
    valid_competition_date = (
        df["CompetitionOpenSinceYear"].notna()
        & df["CompetitionOpenSinceMonth"].notna()
        & (df["CompetitionOpenSinceYear"] != 1900)
    )

    # Indicator showing whether the competition start date is known
    df["CompetitionStartKnown"] = valid_competition_date.astype(int)

    # Build the competition opening date only where it is valid
    competition_start = pd.to_datetime(
        {
            "year": df["CompetitionOpenSinceYear"].where(
                valid_competition_date
            ),
            "month": df["CompetitionOpenSinceMonth"].where(
                valid_competition_date
            ),
            "day": 1
        },
        errors="coerce"
    )

    # Competition is active when its opening date is before or equal to
    # the current observation date
    df["CompetitionActive"] = (
        valid_competition_date
        & (df["Date"] >= competition_start)
    ).astype(int)

    # Number of months since competition opened
    df["MonthsSinceCompetitionOpened"] = np.nan

    active_mask = (
        valid_competition_date
        & (df["Date"] >= competition_start)
    )

    df.loc[active_mask, "MonthsSinceCompetitionOpened"] = (
        (df.loc[active_mask, "Date"].dt.year
         - competition_start.loc[active_mask].dt.year) * 12
        +
        (df.loc[active_mask, "Date"].dt.month
         - competition_start.loc[active_mask].dt.month)
    )

    return df

In [ ]:
train_features = add_competition_features(train_features)

print(
    train_features[
        [
            "Store",
            "Date",
            "CompetitionStartKnown",
            "CompetitionActive",
            "MonthsSinceCompetitionOpened"
        ]
    ].head(10)
)

print("\nNew feature summary:")
display(
    train_features[
        [
            "CompetitionStartKnown",
            "CompetitionActive",
            "MonthsSinceCompetitionOpened"
        ]
    ].describe()
)

In [ ]:
# Store-level summary of the new competition features
competition_store_summary = (
    train_features[
        [
            "Store",
            "CompetitionStartKnown",
            "CompetitionActive",
            "MonthsSinceCompetitionOpened"
        ]
    ]
    .groupby("Store")
    .agg({
        "CompetitionStartKnown": "first",
        "CompetitionActive": "mean",
        "MonthsSinceCompetitionOpened": "mean"
    })
    .reset_index()
)

display(competition_store_summary.head(20))

print("CompetitionStartKnown counts:")
print(
    competition_store_summary["CompetitionStartKnown"]
    .value_counts()
)

print("\nCompetitionActive mean by known-date status:")
print(
    competition_store_summary
    .groupby("CompetitionStartKnown")["CompetitionActive"]
    .mean()
)

In [ ]:
print("Original features:")
print(feature_columns)

print("\nLag features:")
print(lag_features)

print("\nAll lagged-model features:")
print(feature_columns_with_lags)

In [ ]:
lag_correlation = train_features[
    ["Sales_Lag_1", "Sales_Lag_7", "Sales_Rolling_7"]
].corr()

print(lag_correlation)

In [ ]:
lag_feature_groups = {
    "Base": [],
    "Lag_1": ["Sales_Lag_1"],
    "Lag_7": ["Sales_Lag_7"],
    "Rolling_7": ["Sales_Rolling_7"],
    "All_Lag_Features": [
        "Sales_Lag_1",
        "Sales_Lag_7",
        "Sales_Rolling_7"
    ]
}

for name, features in lag_feature_groups.items():
    print(name, ":", features)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression

# Chronological split
train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

# Target
y_train_base = train_features.loc[train_mask, "Sales"]
y_valid_base = train_features.loc[valid_mask, "Sales"]

# Base feature definitions
numeric_features_base = [
    "Open",
    "Promo",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

categorical_features = [
    "StateHoliday"
]

# Preprocessing
numeric_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ]
)

categorical_transformer = Pipeline(
    steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ]
)

print("Training rows:", train_mask.sum())
print("Validation rows:", valid_mask.sum())

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Chronological train/validation masks
train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

# Targets
y_train_base = train_features.loc[train_mask, "Sales"]
y_valid_base = train_features.loc[valid_mask, "Sales"]

# Selected lag features
selected_lag_features = [
    "Sales_Lag_7",
    "Sales_Rolling_7"
]

# Complete feature list
selected_features = feature_columns + selected_lag_features

# Training and validation data
X_train_lag7_roll7 = train_features.loc[
    train_mask,
    selected_features
]

X_valid_lag7_roll7 = train_features.loc[
    valid_mask,
    selected_features
]

# Keep only numerical columns that actually exist
numeric_lag7_roll7 = [
    col for col in numeric_features_base
    if col in selected_features
] + [
    col for col in selected_lag_features
    if col in selected_features
]

# Keep only categorical columns that actually exist
categorical_lag7_roll7 = [
    col for col in categorical_features
    if col in selected_features
]

# Preprocessor
preprocessor_lag7_roll7 = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_transformer,
            numeric_lag7_roll7
        ),
        (
            "cat",
            categorical_transformer,
            categorical_lag7_roll7
        )
    ]
)

# Pipeline
pipeline_lag7_roll7 = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor_lag7_roll7
        ),
        (
            "model",
            LinearRegression()
        )
    ]
)

# Train
pipeline_lag7_roll7.fit(
    X_train_lag7_roll7,
    y_train_base
)

# Predict
y_pred_lag7_roll7 = pipeline_lag7_roll7.predict(
    X_valid_lag7_roll7
)

# Metrics
mae_lag7_roll7 = mean_absolute_error(
    y_valid_base,
    y_pred_lag7_roll7
)

rmse_lag7_roll7 = np.sqrt(
    mean_squared_error(
        y_valid_base,
        y_pred_lag7_roll7
    )
)

r2_lag7_roll7 = r2_score(
    y_valid_base,
    y_pred_lag7_roll7
)

# Results
print("Lag_7 + Rolling_7 Results")
print(f"MAE:  {mae_lag7_roll7:.2f}")
print(f"RMSE: {rmse_lag7_roll7:.2f}")
print(f"R²:   {r2_lag7_roll7:.4f}")

In [ ]:
# Ensure data is sorted correctly
train_features = train_features.sort_values(
    ["Store", "Date"]
).copy()

# Create 14-day lag
train_features["Sales_Lag_14"] = (
    train_features.groupby("Store")["Sales"]
    .shift(14)
)

# Create previous 14-day rolling mean
train_features["Sales_Rolling_14"] = (
    train_features.groupby("Store")["Sales"]
    .transform(
        lambda x: x.shift(1).rolling(14, min_periods=1).mean()
    )
)

print(
    train_features[
        ["Sales_Lag_14", "Sales_Rolling_14"]
    ].isna().sum()
)

print(
    train_features[
        ["Sales_Lag_14", "Sales_Rolling_14"]
    ].head(20)
)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Select the 14-day lag features
selected_lag_features_14 = [
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

# Complete selected feature list
selected_features_14 = feature_columns + selected_lag_features_14

# Train and validation data
X_train_lag14_roll14 = train_features.loc[
    train_mask,
    selected_features_14
]

X_valid_lag14_roll14 = train_features.loc[
    valid_mask,
    selected_features_14
]

# Keep only numerical columns present in this model
numeric_lag14_roll14 = [
    col for col in numeric_features_base
    if col in selected_features_14
] + [
    col for col in selected_lag_features_14
    if col in selected_features_14
]

# Keep only categorical columns present in this model
categorical_lag14_roll14 = [
    col for col in categorical_features
    if col in selected_features_14
]

# Preprocessor
preprocessor_lag14_roll14 = ColumnTransformer(
    transformers=[
        (
            "num",
            Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="median"))
                ]
            ),
            numeric_lag14_roll14
        ),
        (
            "cat",
            Pipeline(
                steps=[
                    (
                        "imputer",
                        SimpleImputer(strategy="most_frequent")
                    ),
                    (
                        "onehot",
                        OneHotEncoder(handle_unknown="ignore")
                    )
                ]
            ),
            categorical_lag14_roll14
        )
    ]
)

# Model pipeline
pipeline_lag14_roll14 = Pipeline(
    steps=[
        ("preprocessor", preprocessor_lag14_roll14),
        ("model", LinearRegression())
    ]
)

# Train
pipeline_lag14_roll14.fit(
    X_train_lag14_roll14,
    y_train_base
)

# Predict
y_pred_lag14_roll14 = pipeline_lag14_roll14.predict(
    X_valid_lag14_roll14
)

# Evaluate
mae_lag14_roll14 = mean_absolute_error(
    y_valid_base,
    y_pred_lag14_roll14
)

rmse_lag14_roll14 = np.sqrt(
    mean_squared_error(
        y_valid_base,
        y_pred_lag14_roll14
    )
)

r2_lag14_roll14 = r2_score(
    y_valid_base,
    y_pred_lag14_roll14
)

print("Lag_14 + Rolling_14 Results")
print(f"MAE:  {mae_lag14_roll14:.2f}")
print(f"RMSE: {rmse_lag14_roll14:.2f}")
print(f"R²:   {r2_lag14_roll14:.4f}")

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# ============================================================
# 1. Select the 14-day lag features
# ============================================================

selected_lag_features_14 = [
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

selected_features_14 = feature_columns + selected_lag_features_14
selected_features_14 = list(dict.fromkeys(selected_features_14))

# ============================================================
# 2. Verify that all selected columns exist
# ============================================================

missing_features_14 = [
    col
    for col in selected_features_14
    if col not in train_features.columns
]

if missing_features_14:
    raise KeyError(
        f"Missing selected features: {missing_features_14}"
    )

# ============================================================
# 3. Chronological train/validation split
# ============================================================

train_mask = (
    train_features["Date"] < pd.Timestamp("2015-06-20")
)

valid_mask = (
    train_features["Date"] >= pd.Timestamp("2015-06-20")
)

# ============================================================
# 4. Prepare training and validation data
# ============================================================

X_train_lag14_roll14 = train_features.loc[
    train_mask,
    selected_features_14
].copy()

X_valid_lag14_roll14 = train_features.loc[
    valid_mask,
    selected_features_14
].copy()

y_train_base = train_features.loc[
    train_mask,
    "Sales"
]

y_valid_base = train_features.loc[
    valid_mask,
    "Sales"
]

# ============================================================
# 5. Correctly identify categorical columns
# ============================================================

categorical_lag14_roll14 = [
    col
    for col in [
        "StateHoliday",
        "StoreType",
        "Assortment",
        "PromoInterval"
    ]
    if col in selected_features_14
]

# All remaining selected columns are numerical
numeric_lag14_roll14 = [
    col
    for col in selected_features_14
    if col not in categorical_lag14_roll14
]

print("Selected features:", selected_features_14)
print("Numerical features:", numeric_lag14_roll14)
print("Categorical features:", categorical_lag14_roll14)

# ============================================================
# 6. Numerical preprocessing
# ============================================================

numeric_pipeline_lag14_roll14 = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="median")
        )
    ]
)

# ============================================================
# 7. Categorical preprocessing
# ============================================================

categorical_pipeline_lag14_roll14 = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(strategy="most_frequent")
        ),
        (
            "onehot",
            OneHotEncoder(handle_unknown="ignore")
        )
    ]
)

# ============================================================
# 8. Column transformer
# ============================================================

preprocessor_lag14_roll14 = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_pipeline_lag14_roll14,
            numeric_lag14_roll14
        ),
        (
            "cat",
            categorical_pipeline_lag14_roll14,
            categorical_lag14_roll14
        )
    ]
)

# ============================================================
# 9. Linear Regression pipeline
# ============================================================

pipeline_lag14_roll14 = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor_lag14_roll14
        ),
        (
            "model",
            LinearRegression()
        )
    ]
)

# ============================================================
# 10. Train
# ============================================================

pipeline_lag14_roll14.fit(
    X_train_lag14_roll14,
    y_train_base
)

# ============================================================
# 11. Predict
# ============================================================

y_pred_lag14_roll14 = pipeline_lag14_roll14.predict(
    X_valid_lag14_roll14
)

# ============================================================
# 12. Evaluate
# ============================================================

mae_lag14_roll14 = mean_absolute_error(
    y_valid_base,
    y_pred_lag14_roll14
)

rmse_lag14_roll14 = np.sqrt(
    mean_squared_error(
        y_valid_base,
        y_pred_lag14_roll14
    )
)

r2_lag14_roll14 = r2_score(
    y_valid_base,
    y_pred_lag14_roll14
)

# ============================================================
# 13. Results
# ============================================================

print("\nLag_14 + Rolling_14 Results")
print(f"MAE:  {mae_lag14_roll14:.2f}")
print(f"RMSE: {rmse_lag14_roll14:.2f}")
print(f"R²:   {r2_lag14_roll14:.4f}")

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np
import pandas as pd

# ============================================================
# 1. Select the 14-day lag features
# ============================================================

selected_lag_features_14 = [
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

selected_features_14 = feature_columns + selected_lag_features_14

# Remove duplicate feature names
selected_features_14 = list(dict.fromkeys(selected_features_14))

# ============================================================
# 2. Check that all selected columns exist
# ============================================================

missing_features_14 = [
    col
    for col in selected_features_14
    if col not in train_features.columns
]

if missing_features_14:
    raise KeyError(
        f"Missing columns in train_features: {missing_features_14}"
    )

# ============================================================
# 3. Chronological train/validation split
# ============================================================

train_mask = (
    train_features["Date"] < pd.Timestamp("2015-06-20")
)

valid_mask = (
    train_features["Date"] >= pd.Timestamp("2015-06-20")
)

# ============================================================
# 4. Prepare X and y
# ============================================================

X_train_lag14_roll14 = train_features.loc[
    train_mask,
    selected_features_14
].copy()

X_valid_lag14_roll14 = train_features.loc[
    valid_mask,
    selected_features_14
].copy()

y_train_base = train_features.loc[
    train_mask,
    "Sales"
]

y_valid_base = train_features.loc[
    valid_mask,
    "Sales"
]

# ============================================================
# 5. Detect feature types from the actual dataframe
# ============================================================

categorical_lag14_roll14 = (
    X_train_lag14_roll14
    .select_dtypes(
        include=["object", "category", "bool"]
    )
    .columns
    .tolist()
)

numeric_lag14_roll14 = (
    X_train_lag14_roll14
    .select_dtypes(
        include=[np.number]
    )
    .columns
    .tolist()
)

print("Selected features:")
print(selected_features_14)

print("\nNumerical features:")
print(numeric_lag14_roll14)

print("\nCategorical features:")
print(categorical_lag14_roll14)

# ============================================================
# 6. Build preprocessing pipelines
# ============================================================

transformers_lag14_roll14 = []

if numeric_lag14_roll14:
    numeric_pipeline_lag14_roll14 = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(strategy="median")
            )
        ]
    )

    transformers_lag14_roll14.append(
        (
            "num",
            numeric_pipeline_lag14_roll14,
            numeric_lag14_roll14
        )
    )

if categorical_lag14_roll14:
    categorical_pipeline_lag14_roll14 = Pipeline(
        steps=[
            (
                "imputer",
                SimpleImputer(strategy="most_frequent")
            ),
            (
                "onehot",
                OneHotEncoder(handle_unknown="ignore")
            )
        ]
    )

    transformers_lag14_roll14.append(
        (
            "cat",
            categorical_pipeline_lag14_roll14,
            categorical_lag14_roll14
        )
    )

# ============================================================
# 7. Column transformer
# ============================================================

preprocessor_lag14_roll14 = ColumnTransformer(
    transformers=transformers_lag14_roll14
)

# ============================================================
# 8. Linear Regression pipeline
# ============================================================

pipeline_lag14_roll14 = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor_lag14_roll14
        ),
        (
            "model",
            LinearRegression()
        )
    ]
)

# ============================================================
# 9. Train
# ============================================================

pipeline_lag14_roll14.fit(
    X_train_lag14_roll14,
    y_train_base
)

# ============================================================
# 10. Predict
# ============================================================

y_pred_lag14_roll14 = pipeline_lag14_roll14.predict(
    X_valid_lag14_roll14
)

# ============================================================
# 11. Evaluate
# ============================================================

mae_lag14_roll14 = mean_absolute_error(
    y_valid_base,
    y_pred_lag14_roll14
)

rmse_lag14_roll14 = np.sqrt(
    mean_squared_error(
        y_valid_base,
        y_pred_lag14_roll14
    )
)

r2_lag14_roll14 = r2_score(
    y_valid_base,
    y_pred_lag14_roll14
)

# ============================================================
# 12. Display results
# ============================================================

print("\n===== LAG 14 + ROLLING 14 RESULTS =====")
print(f"MAE:  {mae_lag14_roll14:.2f}")
print(f"RMSE: {rmse_lag14_roll14:.2f}")
print(f"R²:   {r2_lag14_roll14:.4f}")

In [ ]:
best_lag_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

In [ ]:
# ============================================================
# Random Forest using a 20% training sample
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Best feature combination
best_lag_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

selected_features = feature_columns + best_lag_features

numeric_features = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "SchoolHoliday",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "Year",
    "Month",
    "Day",
    "WeekOfYear"
] + best_lag_features

categorical_features = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

# ------------------------------------------------------------
# 1. Create a 20% sample from the training data
# ------------------------------------------------------------

# Create a 30% sample from the training data
sample_train = train_features.loc[train_mask].sample(
    frac=0.30,
    random_state=42
)

X_train_sample = sample_train[selected_features]
y_train_sample = sample_train["Sales"]

X_valid = train_features.loc[valid_mask, selected_features]
y_valid = train_features.loc[valid_mask, "Sales"]

print("Sample training rows:", len(sample_train))
print("Validation rows:", len(X_valid))

# ------------------------------------------------------------
# 2. Preprocessing
# ------------------------------------------------------------

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

# ------------------------------------------------------------
# 3. Random Forest
# ------------------------------------------------------------

rf_sample_model = RandomForestRegressor(
    n_estimators=100,
    max_depth=20,
    min_samples_leaf=10,
    random_state=42,
    n_jobs=-1
)

rf_sample_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", rf_sample_model)
])

# ------------------------------------------------------------
# 4. Train on sample
# ------------------------------------------------------------

print("Training Random Forest on 20% sample...")

rf_sample_pipeline.fit(
    X_train_sample,
    y_train_sample
)

# ------------------------------------------------------------
# 5. Predict on full validation set
# ------------------------------------------------------------

print("Generating validation predictions...")

sample_predictions = rf_sample_pipeline.predict(X_valid)

# ------------------------------------------------------------
# 6. Evaluate
# ------------------------------------------------------------

sample_mae = mean_absolute_error(y_valid, sample_predictions)

sample_rmse = np.sqrt(
    mean_squared_error(y_valid, sample_predictions)
)

sample_r2 = r2_score(y_valid, sample_predictions)

print("\nRandom Forest — 20% Training Sample")
print("-----------------------------------")
print(f"MAE:  {sample_mae:.2f}")
print(f"RMSE: {sample_rmse:.2f}")
print(f"R²:   {sample_r2:.4f}")

In [ ]:
# ============================================================
# Random Forest — 30% Sample + Expanding Time-Series CV
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Features
# ------------------------------------------------------------

best_lag_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

selected_features = feature_columns + best_lag_features

numeric_features = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "SchoolHoliday",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "Year",
    "Month",
    "Day",
    "WeekOfYear"
] + best_lag_features

categorical_features = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

# ------------------------------------------------------------
# 2. Use only the original training period
# ------------------------------------------------------------

cv_data = train_features.loc[train_mask].copy()

# Sort chronologically
cv_data = cv_data.sort_values("Date").reset_index(drop=True)

# ------------------------------------------------------------
# 3. Create 3 expanding temporal folds
# ------------------------------------------------------------

fold_dates = [
    pd.Timestamp("2014-01-01"),
    pd.Timestamp("2014-10-01"),
    pd.Timestamp("2015-04-01")
]

results = []

for fold, validation_start in enumerate(fold_dates, start=1):

    validation_end = validation_start + pd.DateOffset(months=3)

    fold_train = cv_data[
        cv_data["Date"] < validation_start
    ]

    fold_valid = cv_data[
        (cv_data["Date"] >= validation_start) &
        (cv_data["Date"] < validation_end)
    ]

    # Sample only the training portion
    fold_train_sample = fold_train.sample(
        frac=0.30,
        random_state=42
    )

    X_train = fold_train_sample[selected_features]
    y_train = fold_train_sample["Sales"]

    X_valid = fold_valid[selected_features]
    y_valid = fold_valid["Sales"]

    # --------------------------------------------------------
    # 4. Preprocessing
    # --------------------------------------------------------

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features)
        ]
    )

    # --------------------------------------------------------
    # 5. Random Forest
    # --------------------------------------------------------

    rf_model = RandomForestRegressor(
        n_estimators=100,
        max_depth=20,
        min_samples_leaf=10,
        random_state=42,
        n_jobs=-1
    )

    rf_pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", rf_model)
    ])

    # --------------------------------------------------------
    # 6. Train and evaluate
    # --------------------------------------------------------

    print(
        f"\nFold {fold}: "
        f"Train={len(fold_train_sample):,}, "
        f"Validation={len(fold_valid):,}"
    )

    rf_pipeline.fit(X_train, y_train)

    predictions = rf_pipeline.predict(X_valid)

    mae = mean_absolute_error(y_valid, predictions)

    rmse = np.sqrt(
        mean_squared_error(y_valid, predictions)
    )

    r2 = r2_score(y_valid, predictions)

    results.append({
        "Fold": fold,
        "Train_Rows": len(fold_train_sample),
        "Valid_Rows": len(fold_valid),
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2
    })

    print(f"MAE:  {mae:.2f}")
    print(f"RMSE: {rmse:.2f}")
    print(f"R²:   {r2:.4f}")

# ------------------------------------------------------------
# 7. Summary
# ------------------------------------------------------------

cv_results = pd.DataFrame(results)

print("\nFold Results")
print(cv_results.round(4))

print("\n30% Sample Time-Series CV Summary")
print("----------------------------------")
print(f"Average MAE:  {cv_results['MAE'].mean():.2f}")
print(f"Average RMSE: {cv_results['RMSE'].mean():.2f}")
print(f"Average R²:   {cv_results['R2'].mean():.4f}")
print(f"R² Std:       {cv_results['R2'].std():.4f}")

In [ ]:
# ============================================================
# Random Forest Hyperparameter Tuning — 30% Sample
# ============================================================

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
from itertools import product
from time import time

# ------------------------------------------------------------
# 1. Features
# ------------------------------------------------------------

best_lag_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

selected_features = feature_columns + best_lag_features

numeric_features = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "SchoolHoliday",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "Year",
    "Month",
    "Day",
    "WeekOfYear"
] + best_lag_features

categorical_features = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

# ------------------------------------------------------------
# 2. Create 30% training sample
# ------------------------------------------------------------

sample_train = train_features.loc[train_mask].sample(
    frac=0.30,
    random_state=42
)

X_train = sample_train[selected_features]
y_train = sample_train["Sales"]

X_valid = train_features.loc[valid_mask, selected_features]
y_valid = train_features.loc[valid_mask, "Sales"]

print("Training rows:", len(X_train))
print("Validation rows:", len(X_valid))

# ------------------------------------------------------------
# 3. Hyperparameter grid
# ------------------------------------------------------------

param_grid = list(product(
    [100, 200],       # n_estimators
    [15, 20, 25],     # max_depth
    [5, 10, 20]       # min_samples_leaf
))

results = []

# ------------------------------------------------------------
# 4. Train and evaluate each combination
# ------------------------------------------------------------

for i, (n_estimators, max_depth, min_samples_leaf) in enumerate(param_grid, start=1):

    start_time = time()

    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="median"))
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, numeric_features),
            ("cat", categorical_transformer, categorical_features)
        ]
    )

    rf_model = RandomForestRegressor(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_leaf=min_samples_leaf,
        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", rf_model)
    ])

    pipeline.fit(X_train, y_train)

    predictions = pipeline.predict(X_valid)

    mae = mean_absolute_error(y_valid, predictions)

    rmse = np.sqrt(
        mean_squared_error(y_valid, predictions)
    )

    r2 = r2_score(y_valid, predictions)

    results.append({
        "n_estimators": n_estimators,
        "max_depth": max_depth,
        "min_samples_leaf": min_samples_leaf,
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Time_seconds": time() - start_time
    })

    print(
        f"{i:02d}/{len(param_grid)} | "
        f"Trees={n_estimators}, "
        f"Depth={max_depth}, "
        f"Leaf={min_samples_leaf} | "
        f"RMSE={rmse:.2f}, "
        f"R²={r2:.4f}"
    )

# ------------------------------------------------------------
# 5. Sort and display results
# ------------------------------------------------------------

tuning_results = pd.DataFrame(results).sort_values(
    by="RMSE"
).reset_index(drop=True)

print("\nHyperparameter Tuning Results")
print("-----------------------------")

display(tuning_results.round(4))

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
import time

# Selected features
selected_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

# Full temporal split
train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

X_train = train_features.loc[train_mask, selected_features]
y_train = train_features.loc[train_mask, "Sales"]

X_valid = train_features.loc[valid_mask, selected_features]
y_valid = train_features.loc[valid_mask, "Sales"]

# All selected features are numeric
numeric_features = selected_features

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            Pipeline([
                ("imputer", SimpleImputer(strategy="median"))
            ]),
            numeric_features
        )
    ]
)

model = RandomForestRegressor(
    n_estimators=100,
    max_depth=25,
    min_samples_leaf=20,
    random_state=42,
    n_jobs=-1
)

pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", model)
])

print("Training rows:", len(X_train))
print("Validation rows:", len(X_valid))

start_time = time.time()

pipeline.fit(X_train, y_train)

training_time = time.time() - start_time

y_pred = pipeline.predict(X_valid)

mae = mean_absolute_error(y_valid, y_pred)
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
r2 = r2_score(y_valid, y_pred)

print("\nFull Dataset Random Forest Results")
print("-" * 40)
print(f"MAE:           {mae:.4f}")
print(f"RMSE:          {rmse:.4f}")
print(f"R²:            {r2:.4f}")
print(f"Training time: {training_time:.2f} seconds")

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import TimeSeriesSplit
import numpy as np
import pandas as pd
import time

selected_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

# Keep only valid rows and sort chronologically
data = train_features[
    selected_features + ["Sales", "Date"]
].dropna().sort_values("Date").reset_index(drop=True)

X = data[selected_features]
y = data["Sales"]

tscv = TimeSeriesSplit(n_splits=4)

results = []

for fold, (train_idx, valid_idx) in enumerate(tscv.split(X), start=1):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train = y.iloc[train_idx]
    y_valid = y.iloc[valid_idx]

    model = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("linear_regression", LinearRegression())
    ])

    start_time = time.time()

    model.fit(X_train, y_train)
    y_pred = model.predict(X_valid)

    elapsed = time.time() - start_time

    mae = mean_absolute_error(y_valid, y_pred)
    rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
    r2 = r2_score(y_valid, y_pred)

    results.append({
        "Fold": fold,
        "Train_Rows": len(train_idx),
        "Validation_Rows": len(valid_idx),
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Time_seconds": elapsed
    })

    print(
        f"Fold {fold}: "
        f"MAE={mae:.2f}, "
        f"RMSE={rmse:.2f}, "
        f"R²={r2:.4f}"
    )

results_df = pd.DataFrame(results)

print("\nLinear Regression — Time-Series CV")
print("-" * 45)
print(f"Average MAE:  {results_df['MAE'].mean():.2f}")
print(f"Average RMSE: {results_df['RMSE'].mean():.2f}")
print(f"Average R²:   {results_df['R2'].mean():.4f}")
print(f"R² Std:       {results_df['R2'].std():.4f}")

results_df

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import time

selected_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

X_train = train_features.loc[train_mask, selected_features]
y_train = train_features.loc[train_mask, "Sales"]

X_valid = train_features.loc[valid_mask, selected_features]
y_valid = train_features.loc[valid_mask, "Sales"]

model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("linear_regression", LinearRegression())
])

start_time = time.time()

model.fit(X_train, y_train)
y_pred = model.predict(X_valid)

training_time = time.time() - start_time

mae = mean_absolute_error(y_valid, y_pred)
rmse = np.sqrt(mean_squared_error(y_valid, y_pred))
r2 = r2_score(y_valid, y_pred)

print("Linear Regression — Three Selected Features")
print("-" * 50)
print(f"Training rows: {len(X_train)}")
print(f"Validation rows: {len(X_valid)}")
print(f"MAE:           {mae:.4f}")
print(f"RMSE:          {rmse:.4f}")
print(f"R²:            {r2:.4f}")
print(f"Training time: {training_time:.2f} seconds")

In [ ]:
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import numpy as np
import pandas as pd
import time

In [ ]:
all_features = [
    "Store",
    "DayOfWeek",
    "Open",
    "Promo",
    "StateHoliday",
    "SchoolHoliday",
    "StoreType",
    "Assortment",
    "CompetitionDistance",
    "CompetitionOpenSinceMonth",
    "CompetitionOpenSinceYear",
    "Promo2",
    "Promo2SinceWeek",
    "Promo2SinceYear",
    "PromoInterval",
    "Year",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

categorical_features = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

numeric_features = [
    feature for feature in all_features
    if feature not in categorical_features
]

In [ ]:
train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

X_train = train_features.loc[train_mask, all_features]
X_valid = train_features.loc[valid_mask, all_features]

y_train = train_features.loc[train_mask, "Sales"]
y_valid = train_features.loc[valid_mask, "Sales"]

In [ ]:
preprocessor = ColumnTransformer([
    (
        "numeric",
        Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ]),
        numeric_features
    ),
    (
        "categorical",
        Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ))
        ]),
        categorical_features
    )
])

lr_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

start_time = time.time()

lr_model.fit(X_train, y_train)

baseline_predictions = lr_model.predict(X_valid)

baseline_mae = mean_absolute_error(y_valid, baseline_predictions)
baseline_rmse = np.sqrt(mean_squared_error(y_valid, baseline_predictions))
baseline_r2 = r2_score(y_valid, baseline_predictions)

print(f"Baseline MAE:  {baseline_mae:.4f}")
print(f"Baseline RMSE: {baseline_rmse:.4f}")
print(f"Baseline R²:   {baseline_r2:.4f}")
print(f"Training time: {time.time() - start_time:.2f} seconds")

In [ ]:
importance_sample = X_valid.sample(
    n=min(10000, len(X_valid)),
    random_state=42
)

importance_targets = y_valid.loc[importance_sample.index]

In [ ]:
start_time = time.time()

permutation_result = permutation_importance(
    lr_model,
    importance_sample,
    importance_targets,
    scoring="neg_mean_absolute_error",
    n_repeats=5,
    random_state=42,
    n_jobs=-1
)

print(f"Permutation time: {time.time() - start_time:.2f} seconds")

In [ ]:
importance_df = pd.DataFrame({
    "Feature": all_features,
    "Importance_MAE": permutation_result.importances_mean,
    "Importance_Std": permutation_result.importances_std
})

importance_df = importance_df.sort_values(
    by="Importance_MAE",
    ascending=False
).reset_index(drop=True)

importance_df

In [ ]:
reduced_features_v1 = [
    "Promo",
    "Open",
    "Month",
    "WeekOfYear",
    "Assortment",
    "StoreType",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

In [ ]:
train_mask = train_features["Date"] < pd.Timestamp("2015-06-20")
valid_mask = train_features["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = train_features.loc[train_mask, all_features]
X_valid_full = train_features.loc[valid_mask, all_features]

y_train = train_features.loc[train_mask, "Sales"]
y_valid = train_features.loc[valid_mask, "Sales"]

print("Training rows:", len(X_train_full))
print("Validation rows:", len(X_valid_full))

In [ ]:
def evaluate_lr(feature_list):
    selected_categorical = [
        feature for feature in feature_list
        if feature in categorical_features
    ]

    selected_numeric = [
        feature for feature in feature_list
        if feature not in categorical_features
    ]

    transformers = []

    if selected_numeric:
        numeric_pipeline = Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ])

        transformers.append(
            ("numeric", numeric_pipeline, selected_numeric)
        )

    if selected_categorical:
        categorical_pipeline = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ))
        ])

        transformers.append(
            ("categorical", categorical_pipeline, selected_categorical)
        )

    preprocessor = ColumnTransformer(transformers)

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])

    start_time = time.time()

    model.fit(
        X_train_full[feature_list],
        y_train
    )

    predictions = model.predict(
        X_valid_full[feature_list]
    )

    elapsed_time = time.time() - start_time

    return {
        "Features": feature_list.copy(),
        "Feature_Count": len(feature_list),
        "MAE": mean_absolute_error(y_valid, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_valid, predictions)),
        "R2": r2_score(y_valid, predictions),
        "Time": elapsed_time
    }

In [ ]:
reduced_result_v1 = evaluate_lr(reduced_features_v1)

reduced_result_v1

In [ ]:
features_without_day = [
    feature for feature in all_features
    if feature != "Day"
]

lr_without_day = evaluate_lr(features_without_day)

lr_without_day

In [ ]:
comparison_day = pd.DataFrame([
    {
        "Model": "LR - All Features",
        "Feature_Count": len(all_features),
        "MAE": baseline_mae,
        "RMSE": baseline_rmse,
        "R2": baseline_r2
    },
    {
        "Model": "LR - Without Day",
        "Feature_Count": len(features_without_day),
        "MAE": lr_without_day["MAE"],
        "RMSE": lr_without_day["RMSE"],
        "R2": lr_without_day["R2"]
    }
])

comparison_day

In [ ]:
current_features = [
    feature for feature in all_features
    if feature != "Day"
]

print(current_features)
features_without_dayofweek = [
    feature for feature in current_features
    if feature != "DayOfWeek"
]

lr_without_dayofweek = evaluate_lr(features_without_dayofweek)

lr_without_dayofweek

In [ ]:
features_without_dayofweek = [
    feature for feature in current_features
    if feature != "DayOfWeek"
]

lr_without_dayofweek = evaluate_lr(features_without_dayofweek)

lr_without_dayofweek

In [ ]:
features_without_schoolholiday = [
    feature for feature in current_features
    if feature != "SchoolHoliday"
]

lr_without_schoolholiday = evaluate_lr(
    features_without_schoolholiday
)

lr_without_schoolholiday

In [ ]:
{'Features': ['Store',
  'DayOfWeek',
  'Open',
  'Promo',
  'StateHoliday',
  'StoreType',
  'Assortment',
  'CompetitionDistance',
  'CompetitionOpenSinceMonth',
  'CompetitionOpenSinceYear',
  'Promo2',
  'Promo2SinceWeek',
  'Promo2SinceYear',
  'PromoInterval',
  'Year',
  'Month',
  'WeekOfYear',
  'Sales_Lag_7',
  'Sales_Lag_14',
  'Sales_Rolling_14'],
 'Feature_Count': 20,
 'MAE': 834.2588966426583,
 'RMSE': np.float64(1181.0397067931956),
 'R2': 0.8995338864116913,
 'Time': 4.71904182434082}

In [ ]:
features_without_day_and_dayofweek = [
    feature for feature in all_features
    if feature not in ["Day", "DayOfWeek"]
]

result_without_day_and_dayofweek = evaluate_lr(
    features_without_day_and_dayofweek
)

result_without_day_and_dayofweek

In [ ]:
features_without_schoolholiday = [
    feature for feature in features_without_day_and_dayofweek
    if feature != "SchoolHoliday"
]

result_without_schoolholiday = evaluate_lr(
    features_without_schoolholiday
)

result_without_schoolholiday

In [ ]:
features_without_stateholiday = [
    feature for feature in features_without_schoolholiday
    if feature != "StateHoliday"
]

result_without_stateholiday = evaluate_lr(
    features_without_stateholiday
)

result_without_stateholiday

In [ ]:
features_without_competitiondistance = [
    feature for feature in current_features
    if feature != "CompetitionDistance"
]

result_without_competitiondistance = evaluate_lr(
    features_without_competitiondistance
)

result_without_competitiondistance

In [ ]:
current_features = [
    feature for feature in all_features
    if feature not in ["Day", "DayOfWeek", "SchoolHoliday"]
]

features_without_competitiondistance = [
    feature for feature in current_features
    if feature != "CompetitionDistance"
]

result_without_competitiondistance = evaluate_lr(
    features_without_competitiondistance
)

result_without_competitiondistance

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.inspection import permutation_importance
import pandas as pd
import numpy as np

# Use the original 22 features
feature_list = all_features

categorical_features = [
    "StateHoliday",
    "StoreType",
    "Assortment",
    "PromoInterval"
]

numeric_features = [
    feature for feature in feature_list
    if feature not in categorical_features
]

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            SimpleImputer(strategy="median"),
            numeric_features
        ),
        (
            "cat",
            Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", OneHotEncoder(
                    handle_unknown="ignore",
                    sparse_output=False
                ))
            ]),
            categorical_features
        )
    ]
)

lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LinearRegression())
])

# Fit on the training set
lr_pipeline.fit(
    X_train_full[feature_list],
    y_train
)

# Permutation importance on the training set
train_importance = permutation_importance(
    lr_pipeline,
    X_train_full[feature_list],
    y_train,
    scoring="neg_mean_absolute_error",
    n_repeats=5,
    random_state=42,
    n_jobs=-1
)

importance_df = pd.DataFrame({
    "Feature": feature_list,
    "Importance": train_importance.importances_mean
}).sort_values(
    "Importance",
    ascending=False
).reset_index(drop=True)

importance_df

In [ ]:
features_to_remove = [
    "Assortment",
    "StoreType",
    "CompetitionDistance",
    "Promo2SinceWeek",
    "Year",
    "PromoInterval",
    "CompetitionOpenSinceMonth",
    "Promo2SinceYear",
    "Store",
    "CompetitionOpenSinceYear",
    "Promo2",
    "SchoolHoliday",
    "DayOfWeek"
]

In [ ]:
features_without_weak = [
    feature for feature in all_features
    if feature not in features_to_remove
]

result_without_weak = evaluate_lr(
    features_without_weak
)

result_without_weak

In [ ]:
features_open_promo_calendar = [
    "Open",
    "Promo",
    "WeekOfYear",
    "Month",
    "StateHoliday"
]

print(features_open_promo_calendar)
print("Feature count:", len(features_open_promo_calendar))

result_open_promo_calendar = evaluate_lr(features_open_promo_calendar)
result_open_promo_calendar

In [ ]:
# Work on a fresh copy
features_new = train_features.copy()

# Ensure StateHoliday is clean and categorical
features_new["StateHoliday"] = (
    features_new["StateHoliday"]
    .replace("", np.nan)
    .fillna("0")
    .astype(str)
)

# Interaction features
features_new["Open_Promo"] = (
    features_new["Open"] * features_new["Promo"]
)

features_new["Open_StateHoliday"] = (
    features_new["Open"] *
    features_new["StateHoliday"].isin(["a", "b", "c"]).astype(int)
)

# Cyclical month features
features_new["Month_Sin"] = np.sin(
    2 * np.pi * features_new["Month"] / 12
)

features_new["Month_Cos"] = np.cos(
    2 * np.pi * features_new["Month"] / 12
)

# Cyclical week-of-year features
features_new["WeekOfYear_Sin"] = np.sin(
    2 * np.pi * features_new["WeekOfYear"] / 52
)

features_new["WeekOfYear_Cos"] = np.cos(
    2 * np.pi * features_new["WeekOfYear"] / 52
)

print(features_new[
    [
        "Open_Promo",
        "Open_StateHoliday",
        "Month_Sin",
        "Month_Cos",
        "WeekOfYear_Sin",
        "WeekOfYear_Cos"
    ]
].head())

In [ ]:
train_mask = features_new["Date"] < pd.Timestamp("2015-06-20")
valid_mask = features_new["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = features_new.loc[train_mask].copy()
X_valid_full = features_new.loc[valid_mask].copy()

y_train = features_new.loc[train_mask, "Sales"]
y_valid = features_new.loc[valid_mask, "Sales"]

print("Training shape:", X_train_full.shape)
print("Validation shape:", X_valid_full.shape)

In [ ]:
new_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",
    "Open_Promo",
    "Open_StateHoliday",
    "Month_Sin",
    "Month_Cos",
    "WeekOfYear_Sin",
    "WeekOfYear_Cos"
]

print(new_features)
print("Feature count:", len(new_features))

In [ ]:
result_new_features = evaluate_lr(new_features)
result_new_features

In [ ]:
interaction_features = [
    "Open_Promo",
    "Open_StateHoliday"
]

features_with_interactions_only = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
] + interaction_features

print(features_with_interactions_only)
print("Feature count:", len(features_with_interactions_only))

result_interactions_only = evaluate_lr(
    features_with_interactions_only
)

result_interactions_only

In [ ]:
features_lag_calendar = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

print(features_lag_calendar)
print("Feature count:", len(features_lag_calendar))

result_lag_calendar = evaluate_lr(features_lag_calendar)
result_lag_calendar

In [ ]:
# Use a fresh copy
features_new = train_features.copy()

# Lag/rolling features × store operation and promotion
features_new["Lag7_Open"] = (
    features_new["Sales_Lag_7"] * features_new["Open"]
)

features_new["Lag14_Open"] = (
    features_new["Sales_Lag_14"] * features_new["Open"]
)

features_new["Rolling14_Open"] = (
    features_new["Sales_Rolling_14"] * features_new["Open"]
)

features_new["Lag7_Promo"] = (
    features_new["Sales_Lag_7"] * features_new["Promo"]
)

features_new["Lag14_Promo"] = (
    features_new["Sales_Lag_14"] * features_new["Promo"]
)

features_new["Rolling14_Promo"] = (
    features_new["Sales_Rolling_14"] * features_new["Promo"]
)

print(
    features_new[
        [
            "Lag7_Open",
            "Lag14_Open",
            "Rolling14_Open",
            "Lag7_Promo",
            "Lag14_Promo",
            "Rolling14_Promo"
        ]
    ].head()
)

In [ ]:
# Recreate train/validation matrices from the latest feature-engineered data
train_mask = features_new["Date"] < pd.Timestamp("2015-06-20")
valid_mask = features_new["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = features_new.loc[train_mask].copy()
X_valid_full = features_new.loc[valid_mask].copy()

y_train = features_new.loc[train_mask, "Sales"]
y_valid = features_new.loc[valid_mask, "Sales"]

# Baseline + lag/rolling interaction features
features_lag_interactions = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",
    "Lag7_Open",
    "Lag14_Open",
    "Rolling14_Open",
    "Lag7_Promo",
    "Lag14_Promo",
    "Rolling14_Promo"
]

print("Feature count:", len(features_lag_interactions))

result_lag_interactions = evaluate_lr(features_lag_interactions)
result_lag_interactions

In [ ]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
import time

tscv = TimeSeriesSplit(n_splits=4)

tscv_results = []

for fold, (train_idx, valid_idx) in enumerate(
    tscv.split(features_new), start=1
):
    X_train_fold = features_new.iloc[train_idx][features_lag_interactions]
    X_valid_fold = features_new.iloc[valid_idx][features_lag_interactions]

    y_train_fold = features_new.iloc[train_idx]["Sales"]
    y_valid_fold = features_new.iloc[valid_idx]["Sales"]

    selected_categorical = [
        feature
        for feature in features_lag_interactions
        if feature in categorical_features
    ]

    selected_numeric = [
        feature
        for feature in features_lag_interactions
        if feature not in categorical_features
    ]

    transformers = []

    if selected_numeric:
        numeric_pipeline = Pipeline([
            ("imputer", SimpleImputer(strategy="median"))
        ])

        transformers.append(
            ("numeric", numeric_pipeline, selected_numeric)
        )

    if selected_categorical:
        categorical_pipeline = Pipeline([
            ("imputer", SimpleImputer(strategy="most_frequent")),
            ("encoder", OneHotEncoder(
                handle_unknown="ignore",
                sparse_output=True
            ))
        ])

        transformers.append(
            ("categorical", categorical_pipeline, selected_categorical)
        )

    preprocessor = ColumnTransformer(transformers)

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])

    start_time = time.time()

    model.fit(X_train_fold, y_train_fold)

    predictions = model.predict(X_valid_fold)

    elapsed_time = time.time() - start_time

    tscv_results.append({
        "Fold": fold,
        "Train_Size": len(train_idx),
        "Validation_Size": len(valid_idx),
        "MAE": mean_absolute_error(y_valid_fold, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_valid_fold, predictions)),
        "R2": r2_score(y_valid_fold, predictions),
        "Time": elapsed_time
    })

tscv_results_df = pd.DataFrame(tscv_results)

tscv_results_df

In [ ]:
import inspect

print(inspect.getsource(evaluate_lr))

In [ ]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
import pandas as pd
import time

baseline_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14"
]

interaction_features = features_lag_interactions

feature_sets = {
    "Baseline": baseline_features,
    "Lag/Rolling Interactions": interaction_features
}

tscv = TimeSeriesSplit(n_splits=4)
comparison_results = []

for model_name, feature_list in feature_sets.items():

    for fold, (train_idx, valid_idx) in enumerate(
        tscv.split(features_new), start=1
    ):

        X_train_fold = features_new.iloc[train_idx][feature_list]
        X_valid_fold = features_new.iloc[valid_idx][feature_list]

        y_train_fold = features_new.iloc[train_idx]["Sales"]
        y_valid_fold = features_new.iloc[valid_idx]["Sales"]

        selected_categorical = [
            feature
            for feature in feature_list
            if feature in categorical_features
        ]

        selected_numeric = [
            feature
            for feature in feature_list
            if feature not in categorical_features
        ]

        transformers = []

        if selected_numeric:
            numeric_pipeline = Pipeline([
                ("imputer", SimpleImputer(strategy="median"))
            ])

            transformers.append(
                ("numeric", numeric_pipeline, selected_numeric)
            )

        if selected_categorical:
            categorical_pipeline = Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("encoder", OneHotEncoder(
                    handle_unknown="ignore",
                    sparse_output=True
                ))
            ])

            transformers.append(
                ("categorical", categorical_pipeline, selected_categorical)
            )

        preprocessor = ColumnTransformer(transformers)

        model = Pipeline([
            ("preprocessor", preprocessor),
            ("model", LinearRegression())
        ])

        start_time = time.time()

        model.fit(X_train_fold, y_train_fold)
        predictions = model.predict(X_valid_fold)

        comparison_results.append({
            "Model": model_name,
            "Fold": fold,
            "MAE": mean_absolute_error(y_valid_fold, predictions),
            "RMSE": np.sqrt(mean_squared_error(y_valid_fold, predictions)),
            "R2": r2_score(y_valid_fold, predictions),
            "Time": time.time() - start_time
        })

comparison_df = pd.DataFrame(comparison_results)

comparison_df

In [ ]:
features_new = train_features.copy()

# Recent demand momentum
features_new["Sales_Lag_7_Change"] = (
    features_new["Sales_Lag_7"] - features_new["Sales_Lag_14"]
)

features_new["Sales_Lag_7_Ratio"] = (
    features_new["Sales_Lag_7"]
    / (features_new["Sales_Lag_14"] + 1)
)

features_new["Sales_Rolling_14_Change"] = (
    features_new["Sales_Lag_7"] - features_new["Sales_Rolling_14"]
)

features_new["Sales_Rolling_14_Ratio"] = (
    features_new["Sales_Lag_7"]
    / (features_new["Sales_Rolling_14"] + 1)
)

features_new["Sales_Trend_Strength"] = (
    features_new["Sales_Lag_7"]
    - features_new["Sales_Lag_14"]
).abs()

In [ ]:
features_new[
    [
        "Sales_Lag_7",
        "Sales_Lag_14",
        "Sales_Rolling_14",
        "Sales_Lag_7_Change",
        "Sales_Lag_7_Ratio",
        "Sales_Rolling_14_Change",
        "Sales_Rolling_14_Ratio",
        "Sales_Trend_Strength"
    ]
].head(20)

In [ ]:
# Demand volatility and consistency

features_new["Sales_Rolling_7"] = (
    features_new["Sales_Lag_7"]
    .rolling(window=7, min_periods=1)
    .mean()
)

features_new["Sales_Demand_Volatility"] = (
    features_new["Sales_Lag_7"]
    - features_new["Sales_Lag_14"]
).abs()

features_new["Sales_Demand_Stability"] = (
    features_new["Sales_Rolling_14"]
    / (features_new["Sales_Lag_7"].abs() + 1)
)

features_new["Sales_Demand_Acceleration"] = (
    features_new["Sales_Lag_7"]
    - 2 * features_new["Sales_Lag_14"]
    + features_new["Sales_Rolling_14"]
)

In [ ]:
features_new[
    [
        "Sales_Lag_7",
        "Sales_Lag_14",
        "Sales_Rolling_14",
        "Sales_Rolling_7",
        "Sales_Demand_Volatility",
        "Sales_Demand_Stability",
        "Sales_Demand_Acceleration"
    ]
].head(20)

In [ ]:
# Demand × operating conditions

features_new["Lag7_Open_Ratio"] = (
    features_new["Sales_Lag_7"] * features_new["Open"]
)

features_new["Lag14_Open_Ratio"] = (
    features_new["Sales_Lag_14"] * features_new["Open"]
)

features_new["Rolling14_Open_Ratio"] = (
    features_new["Sales_Rolling_14"] * features_new["Open"]
)

features_new["Lag7_Promo_Ratio"] = (
    features_new["Sales_Lag_7"] * features_new["Promo"]
)

features_new["Lag14_Promo_Ratio"] = (
    features_new["Sales_Lag_14"] * features_new["Promo"]
)

features_new["Rolling14_Promo_Ratio"] = (
    features_new["Sales_Rolling_14"] * features_new["Promo"]
)

In [ ]:
features_new[
    [
        "Sales_Lag_7",
        "Sales_Lag_14",
        "Sales_Rolling_14",
        "Open",
        "Promo",
        "Lag7_Open_Ratio",
        "Lag14_Open_Ratio",
        "Rolling14_Open_Ratio",
        "Lag7_Promo_Ratio",
        "Lag14_Promo_Ratio",
        "Rolling14_Promo_Ratio"
    ]
].head(20)

In [ ]:
# Ensure chronological order
features_new = features_new.sort_values(
    ["Store", "Date"]
).reset_index(drop=True)

# Historical store demand
features_new["Store_Sales_Mean"] = (
    features_new.groupby("Store")["Sales"]
    .transform(lambda s: s.shift(1).expanding().mean())
)

features_new["Store_Sales_Median"] = (
    features_new.groupby("Store")["Sales"]
    .transform(lambda s: s.shift(1).expanding().median())
)

features_new["Store_Sales_Max"] = (
    features_new.groupby("Store")["Sales"]
    .transform(lambda s: s.shift(1).expanding().max())
)

features_new["Store_Sales_Min"] = (
    features_new.groupby("Store")["Sales"]
    .transform(lambda s: s.shift(1).expanding().min())
)

In [ ]:
features_new[
    [
        "Store",
        "Date",
        "Sales",
        "Store_Sales_Mean",
        "Store_Sales_Median",
        "Store_Sales_Max",
        "Store_Sales_Min"
    ]
].head(20)

In [ ]:
store_demand_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",
    "Store_Sales_Mean",
    "Store_Sales_Median"
]

# Recreate train/validation data using the updated features_new

train_mask = features_new["Date"] < pd.Timestamp("2015-06-20")
valid_mask = features_new["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = features_new.loc[train_mask].copy()
X_valid_full = features_new.loc[valid_mask].copy()

y_train = features_new.loc[train_mask, "Sales"]
y_valid = features_new.loc[valid_mask, "Sales"]

print("Train shape:", X_train_full.shape)
print("Validation shape:", X_valid_full.shape)

In [ ]:
result_store_demand = evaluate_lr(store_demand_features)

result_store_demand

In [ ]:
# Day-of-week demand features

features_new["DayOfWeek"] = features_new["Date"].dt.dayofweek

features_new["Sales_Lag_7_DayOfWeek"] = (
    features_new["Sales_Lag_7"] * features_new["DayOfWeek"]
)

features_new["Sales_Lag_14_DayOfWeek"] = (
    features_new["Sales_Lag_14"] * features_new["DayOfWeek"]
)

features_new["Rolling14_DayOfWeek"] = (
    features_new["Sales_Rolling_14"] * features_new["DayOfWeek"]
)

In [ ]:
features_new[
    [
        "Date",
        "DayOfWeek",
        "Sales_Lag_7",
        "Sales_Lag_14",
        "Sales_Rolling_14",
        "Sales_Lag_7_DayOfWeek",
        "Sales_Lag_14_DayOfWeek",
        "Rolling14_DayOfWeek"
    ]
].head(20)

In [ ]:
# Recreate chronological train/validation data

features_new = features_new.sort_values("Date").reset_index(drop=True)

train_mask = features_new["Date"] < pd.Timestamp("2015-06-20")
valid_mask = features_new["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = features_new.loc[train_mask].copy()
X_valid_full = features_new.loc[valid_mask].copy()

y_train = features_new.loc[train_mask, "Sales"]
y_valid = features_new.loc[valid_mask, "Sales"]

In [ ]:
day_of_week_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",
    "Sales_Lag_7_DayOfWeek",
    "Sales_Lag_14_DayOfWeek",
    "Rolling14_DayOfWeek"
]

day_of_week_result = evaluate_lr(day_of_week_features)

pd.DataFrame([day_of_week_result])

In [ ]:
# Recreate lag interaction features

features_new["Lag7_Open"] = (
    features_new["Sales_Lag_7"] * features_new["Open"]
)

features_new["Lag14_Open"] = (
    features_new["Sales_Lag_14"] * features_new["Open"]
)

features_new["Rolling14_Open"] = (
    features_new["Sales_Rolling_14"] * features_new["Open"]
)

features_new["Lag7_Promo"] = (
    features_new["Sales_Lag_7"] * features_new["Promo"]
)

features_new["Lag14_Promo"] = (
    features_new["Sales_Lag_14"] * features_new["Promo"]
)

features_new["Rolling14_Promo"] = (
    features_new["Sales_Rolling_14"] * features_new["Promo"]
)

In [ ]:
features_new = features_new.sort_values("Date").reset_index(drop=True)

train_mask = features_new["Date"] < pd.Timestamp("2015-06-20")
valid_mask = features_new["Date"] >= pd.Timestamp("2015-06-20")

X_train_full = features_new.loc[train_mask].copy()
X_valid_full = features_new.loc[valid_mask].copy()

y_train = features_new.loc[train_mask, "Sales"]
y_valid = features_new.loc[valid_mask, "Sales"]

In [ ]:
combined_features = [
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_7",
    "Sales_Rolling_14",
    "Promo",
    "Open",
    "DayOfWeek",
    "Month",
    "Year",
    "CompetitionDistance"
]

combined_result = evaluate_lr(combined_features)

pd.DataFrame([combined_result])

In [ ]:
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd

tscv = TimeSeriesSplit(n_splits=4)

fold_results = []

X = features_new[combined_features]
y = features_new["Sales"]

for fold, (train_idx, valid_idx) in enumerate(tscv.split(X), start=1):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train_fold = y.iloc[train_idx]
    y_valid_fold = y.iloc[valid_idx]

    selected_categorical = [
        feature for feature in combined_features
        if feature in categorical_features
    ]

    selected_numeric = [
        feature for feature in combined_features
        if feature not in categorical_features
    ]

    transformers = []

    if selected_numeric:
        transformers.append(
            (
                "numeric",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median"))
                ]),
                selected_numeric
            )
        )

    if selected_categorical:
        transformers.append(
            (
                "categorical",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("encoder", OneHotEncoder(
                        handle_unknown="ignore",
                        sparse_output=True
                    ))
                ]),
                selected_categorical
            )
        )

    preprocessor = ColumnTransformer(transformers)

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])

    model.fit(X_train, y_train_fold)

    predictions = model.predict(X_valid)

    fold_results.append({
        "Fold": fold,
        "MAE": mean_absolute_error(y_valid_fold, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_valid_fold, predictions)),
        "R2": r2_score(y_valid_fold, predictions)
    })

tscv_combined_results = pd.DataFrame(fold_results)

display(tscv_combined_results)

print("\nAverage results:")
display(tscv_combined_results.mean(numeric_only=True).to_frame().T)

In [ ]:
lag_promo_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",

    "Lag7_Open",
    "Lag14_Open",
    "Rolling14_Open",

    "Lag7_Promo",
    "Lag14_Promo",
    "Rolling14_Promo"
]

lag_promo_result = evaluate_lr(lag_promo_features)

pd.DataFrame([lag_promo_result])

In [ ]:
tscv = TimeSeriesSplit(n_splits=4)

fold_results = []

X = features_new[lag_promo_features]
y = features_new["Sales"]

for fold, (train_idx, valid_idx) in enumerate(tscv.split(X), start=1):

    X_train = X.iloc[train_idx]
    X_valid = X.iloc[valid_idx]

    y_train_fold = y.iloc[train_idx]
    y_valid_fold = y.iloc[valid_idx]

    selected_categorical = [
        feature for feature in lag_promo_features
        if feature in categorical_features
    ]

    selected_numeric = [
        feature for feature in lag_promo_features
        if feature not in categorical_features
    ]

    transformers = []

    if selected_numeric:
        transformers.append(
            (
                "numeric",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="median"))
                ]),
                selected_numeric
            )
        )

    if selected_categorical:
        transformers.append(
            (
                "categorical",
                Pipeline([
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("encoder", OneHotEncoder(
                        handle_unknown="ignore",
                        sparse_output=True
                    ))
                ]),
                selected_categorical
            )
        )

    preprocessor = ColumnTransformer(transformers)

    model = Pipeline([
        ("preprocessor", preprocessor),
        ("model", LinearRegression())
    ])

    model.fit(X_train, y_train_fold)

    predictions = model.predict(X_valid)

    fold_results.append({
        "Fold": fold,
        "MAE": mean_absolute_error(y_valid_fold, predictions),
        "RMSE": np.sqrt(mean_squared_error(y_valid_fold, predictions)),
        "R2": r2_score(y_valid_fold, predictions)
    })

tscv_lag_promo_results = pd.DataFrame(fold_results)

display(tscv_lag_promo_results)

print("\nAverage results:")
display(
    tscv_lag_promo_results
    .mean(numeric_only=True)
    .to_frame()
    .T
)

In [ ]:
# ============================================================
# Random Forest + Demand Trend Features
# Training on 50% of the training data
# ============================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np
import pandas as pd
import time


# ------------------------------------------------------------
# 1. Feature set
# ------------------------------------------------------------

rf_trend_features = [
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",

    "Lag7_Open",
    "Lag14_Open",
    "Rolling14_Open",

    "Lag7_Promo",
    "Lag14_Promo",
    "Rolling14_Promo",

    "Sales_Lag_7_Change",
    "Sales_Lag_7_Ratio",
    "Sales_Rolling_14_Change",
    "Sales_Rolling_14_Ratio",
    "Sales_Trend_Strength"
]


# ------------------------------------------------------------
# 2. Take a 50% sample from training data
#    Validation data remains unchanged
# ------------------------------------------------------------

X_train_sample = X_train_full.sample(
    frac=0.50,
    random_state=42
)

y_train_sample = y_train.loc[X_train_sample.index]

print("Original training rows:", len(X_train_full))
print("Sampled training rows:", len(X_train_sample))
print("Validation rows:", len(X_valid_full))


# ------------------------------------------------------------
# 3. Separate numeric and categorical features
# ------------------------------------------------------------

selected_categorical = [
    feature
    for feature in rf_trend_features
    if feature in categorical_features
]

selected_numeric = [
    feature
    for feature in rf_trend_features
    if feature not in categorical_features
]


# ------------------------------------------------------------
# 4. Build preprocessing pipeline
# ------------------------------------------------------------

transformers = []

if selected_numeric:
    numeric_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ])

    transformers.append(
        (
            "numeric",
            numeric_pipeline,
            selected_numeric
        )
    )

if selected_categorical:
    categorical_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ])

    transformers.append(
        (
            "categorical",
            categorical_pipeline,
            selected_categorical
        )
    )


preprocessor = ColumnTransformer(transformers)


# ------------------------------------------------------------
# 5. Build Random Forest model
# ------------------------------------------------------------

rf_model = Pipeline([
    ("preprocessor", preprocessor),

    ("model", RandomForestRegressor(
        n_estimators=200,
        max_depth=None,
        min_samples_leaf=2,
        max_features="sqrt",
        n_jobs=-1,
        random_state=42
    ))
])


# ------------------------------------------------------------
# 6. Train on 50% sample
# ------------------------------------------------------------

start_time = time.time()

rf_model.fit(
    X_train_sample[rf_trend_features],
    y_train_sample
)


# ------------------------------------------------------------
# 7. Predict on unchanged validation set
# ------------------------------------------------------------

rf_predictions = rf_model.predict(
    X_valid_full[rf_trend_features]
)


# ------------------------------------------------------------
# 8. Evaluate
# ------------------------------------------------------------

rf_trend_result_50 = {
    "Model": "Random Forest + trend features — 50% sample",
    "Feature_Count": len(rf_trend_features),
    "Training_Rows": len(X_train_sample),
    "MAE": mean_absolute_error(y_valid, rf_predictions),
    "RMSE": np.sqrt(mean_squared_error(y_valid, rf_predictions)),
    "R2": r2_score(y_valid, rf_predictions),
    "Time": time.time() - start_time
}

pd.DataFrame([rf_trend_result_50])

In [ ]:
# ============================================================
# Random Forest with all demand feature groups
# 50% training sample
# ============================================================

from sklearn.ensemble import RandomForestRegressor
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import numpy as np
import pandas as pd
import time


# ------------------------------------------------------------
# 1. All feature groups
# ------------------------------------------------------------

rf_all_features = [
    # Basic operating and calendar features
    "Open",
    "Promo",
    "StateHoliday",
    "Month",
    "Day",
    "WeekOfYear",

    # Historical demand
    "Sales_Lag_7",
    "Sales_Lag_14",
    "Sales_Rolling_14",

    # Demand operating-condition interactions
    "Lag7_Open",
    "Lag14_Open",
    "Rolling14_Open",
    "Lag7_Promo",
    "Lag14_Promo",
    "Rolling14_Promo",

    # Recent demand momentum
    "Sales_Lag_7_Change",
    "Sales_Lag_7_Ratio",
    "Sales_Rolling_14_Change",
    "Sales_Rolling_14_Ratio",
    "Sales_Trend_Strength",

    # Demand volatility and stability
    "Sales_Rolling_7",
    "Sales_Demand_Volatility",
    "Sales_Demand_Stability",
    "Sales_Demand_Acceleration",

    # Historical store demand
    "Store_Sales_Mean",
    "Store_Sales_Median",
    "Store_Sales_Max",
    "Store_Sales_Min"
]


# ------------------------------------------------------------
# 2. Check that every feature exists
# ------------------------------------------------------------

missing_features = [
    feature
    for feature in rf_all_features
    if feature not in features_new.columns
]

if missing_features:
    raise KeyError(
        f"Missing features: {missing_features}"
    )

print("Total features:", len(rf_all_features))


# ------------------------------------------------------------
# 3. Take 50% of training data
# ------------------------------------------------------------

X_train_sample = X_train_full.sample(
    frac=0.50,
    random_state=42
)

y_train_sample = y_train.loc[X_train_sample.index]

print("Original training rows:", len(X_train_full))
print("Sampled training rows:", len(X_train_sample))
print("Validation rows:", len(X_valid_full))


# ------------------------------------------------------------
# 4. Separate numeric and categorical features
# ------------------------------------------------------------

selected_categorical = [
    feature
    for feature in rf_all_features
    if feature in categorical_features
]

selected_numeric = [
    feature
    for feature in rf_all_features
    if feature not in categorical_features
]


# ------------------------------------------------------------
# 5. Preprocessing
# ------------------------------------------------------------

transformers = []

if selected_numeric:
    numeric_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median"))
    ])

    transformers.append(
        (
            "numeric",
            numeric_pipeline,
            selected_numeric
        )
    )

if selected_categorical:
    categorical_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("encoder", OneHotEncoder(
            handle_unknown="ignore",
            sparse_output=False
        ))
    ])

    transformers.append(
        (
            "categorical",
            categorical_pipeline,
            selected_categorical
        )
    )


preprocessor = ColumnTransformer(transformers)


# ------------------------------------------------------------
# 6. Random Forest
# ------------------------------------------------------------

rf_all_model = Pipeline([
    ("preprocessor", preprocessor),

    ("model", RandomForestRegressor(
        n_estimators=200,
        max_depth=None,
        min_samples_leaf=2,
        max_features="sqrt",
        n_jobs=-1,
        random_state=42
    ))
])


# ------------------------------------------------------------
# 7. Train
# ------------------------------------------------------------

start_time = time.time()

rf_all_model.fit(
    X_train_sample[rf_all_features],
    y_train_sample
)


# ------------------------------------------------------------
# 8. Predict
# ------------------------------------------------------------

rf_all_predictions = rf_all_model.predict(
    X_valid_full[rf_all_features]
)


# ------------------------------------------------------------
# 9. Evaluate
# ------------------------------------------------------------

rf_all_result = {
    "Model": "Random Forest + all demand feature groups — 50% sample",
    "Feature_Count": len(rf_all_features),
    "Training_Rows": len(X_train_sample),
    "MAE": mean_absolute_error(y_valid, rf_all_predictions),
    "RMSE": np.sqrt(mean_squared_error(y_valid, rf_all_predictions)),
    "R2": r2_score(y_valid, rf_all_predictions),
    "Time": time.time() - start_time
}

pd.DataFrame([rf_all_result])

In [ ]:
# ============================================================
# Random Forest Feature Importance
# ============================================================

# Get the fitted Random Forest
rf_estimator = rf_all_model.named_steps["model"]

# Get the fitted preprocessing transformer
fitted_preprocessor = rf_all_model.named_steps["preprocessor"]

# Get feature names after preprocessing
transformed_feature_names = (
    fitted_preprocessor.get_feature_names_out()
)

# Extract importance values
importance_values = rf_estimator.feature_importances_

# Create importance table
importance_df = pd.DataFrame({
    "Feature": transformed_feature_names,
    "Importance": importance_values
})

# Sort from most to least important
importance_df = importance_df.sort_values(
    "Importance",
    ascending=False
).reset_index(drop=True)

# Display all features
display(importance_df)

In [ ]:
import matplotlib.pyplot as plt

top20_importance = importance_df.head(20).sort_values(
    "Importance"
)

plt.figure(figsize=(10, 7))

plt.barh(
    top20_importance["Feature"],
    top20_importance["Importance"]
)

plt.xlabel("Feature Importance")
plt.ylabel("Feature")
plt.title("Top 20 Random Forest Feature Importances")

plt.tight_layout()
plt.show()

In [ ]:
import time
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --------------------------------------------------
# 1. Selected features
# --------------------------------------------------

rf_selected_features = [
    "Rolling14_Open",
    "Lag14_Open",
    "Open",
    "Sales_Lag_14",
    "Lag7_Open",
    "Rolling14_Promo",
    "Lag14_Promo",
    "Store_Sales_Mean",
    "Store_Sales_Median",
    "Sales_Lag_7",
    "Sales_Rolling_14",
    "Sales_Demand_Volatility",
    "Sales_Trend_Strength",
    "Lag7_Promo",
    "Sales_Rolling_7",
    "Sales_Rolling_14_Ratio",
    "Day",
    "Sales_Rolling_14_Change",
    "Sales_Demand_Stability",
    "Promo",
    "Store_Sales_Max",
    "Sales_Lag_7_Ratio",
    "Sales_Demand_Acceleration"
]

# --------------------------------------------------
# 2. Prepare features and target
# --------------------------------------------------

rf_data = train_features.copy()

available_features = [
    feature for feature in rf_selected_features
    if feature in rf_data.columns
]

missing_features = [
    feature for feature in rf_selected_features
    if feature not in rf_data.columns
]

print("Available features:", len(available_features))
print("Missing features:", missing_features)

X = rf_data[available_features].copy()
y = rf_data["Sales"].copy()

# --------------------------------------------------
# 3. Train/test split — final 20% as test set
# --------------------------------------------------

split_index = int(len(X) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print("Training shape:", X_train.shape)
print("Testing shape:", X_test.shape)

# --------------------------------------------------
# 4. Detect data types
# --------------------------------------------------

numeric_features = X_train.select_dtypes(
    include=[np.number]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["object", "category", "bool"]
).columns.tolist()

# --------------------------------------------------
# 5. Preprocessing
# --------------------------------------------------

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(
        handle_unknown="ignore",
        sparse_output=False
    ))
])

preprocessor = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

# --------------------------------------------------
# 6. Random Forest model
# --------------------------------------------------

rf_model = RandomForestRegressor(
    n_estimators=100,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", rf_model)
])

# --------------------------------------------------
# 7. Train once and evaluate once
# --------------------------------------------------

start_time = time.time()

rf_pipeline.fit(X_train, y_train)
predictions = rf_pipeline.predict(X_test)

elapsed_time = time.time() - start_time

mae = mean_absolute_error(y_test, predictions)
rmse = np.sqrt(mean_squared_error(y_test, predictions))
r2 = r2_score(y_test, predictions)

print("\nRandom Forest — Selected Features")
print(f"MAE:  ️{mae:.6f}")
print(f"RMSE: {rmse:.6f}")
print(f"R²:   {r2:.6f}")
print(f"Time: {elapsed_time:.2f} seconds")

In [ ]:
import time
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --------------------------------------------------
# Features currently available
# --------------------------------------------------

rf_features = [
    "Open",
    "Sales_Lag_14",
    "Sales_Lag_7",
    "Sales_Rolling_14",
    "Sales_Rolling_7",
    "Day",
    "Promo"
]

X = train_features[rf_features].copy()
y = train_features["Sales"].copy()

# --------------------------------------------------
# 5 chronological folds
# --------------------------------------------------

n_samples = len(X)
fold_size = n_samples // 5

results = []

for fold in range(5):

    train_end = fold_size * (fold + 1)

    # Last fold uses all remaining observations
    valid_start = train_end
    valid_end = (
        fold_size * (fold + 2)
        if fold < 4
        else n_samples
    )

    X_train_full = X.iloc[:train_end]
    y_train_full = y.iloc[:train_end]

    X_valid = X.iloc[valid_start:valid_end]
    y_valid = y.iloc[valid_start:valid_end]

    # --------------------------------------------------
    # Randomly sample 20% from training fold
    # --------------------------------------------------

    sample_size = int(len(X_train_full) * 0.20)

    rng = np.random.RandomState(42 + fold)
    sampled_indices = rng.choice(
        len(X_train_full),
        size=sample_size,
        replace=False
    )

    X_train = X_train_full.iloc[sampled_indices]
    y_train = y_train_full.iloc[sampled_indices]

    print(
        f"\nFold {fold} | "
        f"Full train: {len(X_train_full)} | "
        f"Sampled train: {len(X_train)} | "
        f"Validation: {len(X_valid)}"
    )

    model = RandomForestRegressor(
        n_estimators=100,
        max_features="sqrt",
        random_state=42,
        n_jobs=-1
    )

    start_time = time.time()

    model.fit(X_train, y_train)
    predictions = model.predict(X_valid)

    elapsed_time = time.time() - start_time

    mae = mean_absolute_error(y_valid, predictions)
    rmse = np.sqrt(mean_squared_error(y_valid, predictions))
    r2 = r2_score(y_valid, predictions)

    results.append({
        "Fold": fold,
        "Full_Train_Size": len(X_train_full),
        "Sampled_Train_Size": len(X_train),
        "Validation_Size": len(X_valid),
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Time_sec": elapsed_time
    })

    print(f"MAE:  {mae:.6f}")
    print(f"RMSE: {rmse:.6f}")
    print(f"R²:   {r2:.6f}")
    print(f"Time: {elapsed_time:.2f} sec")

# --------------------------------------------------
# Summary
# --------------------------------------------------

rf_sample_results = pd.DataFrame(results)

print("\nFold Results:")
display(rf_sample_results)

print("\nAverage Results:")
print(f"Average MAE:  {rf_sample_results['MAE'].mean():.6f}")
print(f"Average RMSE: {rf_sample_results['RMSE'].mean():.6f}")
print(f"Average R²:   {rf_sample_results['R2'].mean():.6f}")
print(f"Average Time: {rf_sample_results['Time_sec'].mean():.6f} sec")

In [ ]:
import time
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# --------------------------------------------------
# Features
# --------------------------------------------------

rf_features = [
    "Open",
    "Sales_Lag_14",
    "Sales_Lag_7",
    "Sales_Rolling_14",
    "Sales_Rolling_7",
    "Day",
    "Promo"
]

X = train_features[rf_features].copy()
y = train_features["Sales"].copy()

# --------------------------------------------------
# Five chronological folds
# --------------------------------------------------

n_samples = len(X)
fold_size = n_samples // 5
total_folds = 5

results = []

for fold in range(total_folds):

    # First fold: train on the first 20%, validate on the second 20%
    train_start = 0
    train_end = fold_size * (fold + 1)

    valid_start = train_end
    valid_end = (
        fold_size * (fold + 2)
        if fold < total_folds - 1
        else n_samples
    )

    X_train = X.iloc[train_start:train_end]
    y_train = y.iloc[train_start:train_end]

    X_valid = X.iloc[valid_start:valid_end]
    y_valid = y.iloc[valid_start:valid_end]

    print("\n" + "=" * 70)
    print(f"STARTING FOLD {fold + 1}/{total_folds}")
    print(f"Training rows:   {len(X_train):,}")
    print(f"Validation rows: {len(X_valid):,}")
    print("=" * 70)

    model = RandomForestRegressor(
        n_estimators=100,
        max_features="sqrt",
        random_state=42,
        n_jobs=-1
    )

    start_time = time.time()

    model.fit(X_train, y_train)
    predictions = model.predict(X_valid)

    elapsed_time = time.time() - start_time

    mae = mean_absolute_error(y_valid, predictions)
    rmse = np.sqrt(mean_squared_error(y_valid, predictions))
    r2 = r2_score(y_valid, predictions)

    results.append({
        "Fold": fold + 1,
        "Train_Size": len(X_train),
        "Validation_Size": len(X_valid),
        "MAE": mae,
        "RMSE": rmse,
        "R2": r2,
        "Time_sec": elapsed_time
    })

    progress = ((fold + 1) / total_folds) * 100

    print("\n" + "-" * 70)
    print(f"FOLD {fold + 1} COMPLETED")
    print(f"MAE:       {mae:.6f}")
    print(f"RMSE:      {rmse:.6f}")
    print(f"R²:        {r2:.6f}")
    print(f"Time:      {elapsed_time:.2f} seconds")
    print(f"PROGRESS:  {fold + 1}/{total_folds} folds completed ({progress:.0f}%)")
    print("-" * 70)

    # Display all completed fold results so far
    display(pd.DataFrame(results))

# --------------------------------------------------
# Final summary
# --------------------------------------------------

rf_full_results = pd.DataFrame(results)

print("\n" + "=" * 70)
print("FINAL RESULTS — 5 FOLDS")
print("=" * 70)

display(rf_full_results)

print(f"Average MAE:  {rf_full_results['MAE'].mean():.6f}")
print(f"Average RMSE: {rf_full_results['RMSE'].mean():.6f}")
print(f"Average R²:   {rf_full_results['R2'].mean():.6f}")
print(f"Average Time: {rf_full_results['Time_sec'].mean():.6f} sec")

In [ ]:
import joblib

joblib.dump(rf_model, "random_forest_sales_model.pkl")
print("Model saved successfully.")

In [ ]:
joblib.dump(rf_features, "random_forest_features.pkl")
print("Features saved successfully.")

In [ ]:
import time
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Features used in the current RF experiment
rf_features = [
    "Open",
    "Sales_Lag_14",
    "Sales_Lag_7",
    "Sales_Rolling_14",
    "Sales_Rolling_7",
    "Day",
    "Promo"
]

# Remove rows with missing values
rf_data = train_features[rf_features + ["Sales"]].dropna().reset_index(drop=True)

X = rf_data[rf_features]
y = rf_data["Sales"]

n_samples = len(rf_data)

# Four expanding temporal folds
fold_size = n_samples // 5

results = []

for fold in range(4):
    train_end = fold_size * (fold + 1)
    valid_start = train_end
    valid_end = fold_size * (fold + 2)

    X_train = X.iloc[:train_end]
    y_train = y.iloc[:train_end]

    X_valid = X.iloc[valid_start:valid_end]
    y_valid = y.iloc[valid_start:valid_end]

    start_time = time.time()

    rf_model = RandomForestRegressor(
        n_estimators=100,
        max_depth=None,
        min_samples_leaf=1,
        random_state=42,
        n_jobs=-1
    )

    rf_model.fit(X_train, y_train)

    predictions = rf_model.predict(X_valid)

    elapsed_time = time.time() - start_time

    mae = mean_absolute_error(y_valid, predictions)
    rmse = np.sqrt(mean_squared_error(y_valid, predictions))
    r2 = r2_score(y_valid, predictions)

    results.append({
        "Fold": fold + 1,
        "Train Size": len(X_train),
        "Validation Size": len(X_valid),
        "MAE": mae,
        "RMSE": rmse,
        "R²": r2,
        "Time (sec)": elapsed_time
    })

    print(
        f"Fold {fold + 1} | "
        f"Train: {len(X_train)} | "
        f"Validation: {len(X_valid)} | "
        f"MAE: {mae:.4f} | "
        f"RMSE: {rmse:.4f} | "
        f"R²: {r2:.4f} | "
        f"Time: {elapsed_time:.2f}s"
    )

results_df = pd.DataFrame(results)

print("\nValid-fold averages:")
print(f"Average MAE: {results_df['MAE'].mean():.4f}")
print(f"Average RMSE: {results_df['RMSE'].mean():.4f}")
print(f"Average R²: {results_df['R²'].mean():.4f}")
print(f"Average Time: {results_df['Time (sec)'].mean():.2f}s")

results_df


# ConclusionThe Random Forest model performed well in sales prediction, achieving an R² of 94% on the test set.Cross-validation also showed consistently strong performance across the valid time-based folds, with R² around 92–94%. This means the model is stable and generalizes well to future data.Overall, the model is accurate, reliable, and suitable for sales forecasting.